### ISSUE TITLE
Ransac on Apple Silicon ...

### ISSUE THREAD

**Issue by sebmavro** [LiangliangNan/Easy3D#100]
Hello, congratulations for this work!
I have compiler issues with the "3rd_party/ransac" library on an Apple Silicon processor.  Do you know a solution? Maybe a compilation option? If not, would it be possible to replace it by another one? Thanks.

**Comment by LiangliangNan** [comment]
Hi, thanks for creating this issue!
But I don't see any useful information. What "issue" is it?  Can you please provide the following information about the issue (without this information, it is not possible to know what actually happens)?

- a brief description of the issue;
- operating system name and version (e.g. Windows 10 64-bit or Ubuntu 18.10);
- compiler name and version (e.g., Visual C++ 2015 Update 2);
- Easy3D release version (e.g., 2.4.3) if you are using an official release of Easy3D. Otherwise, the Easy3D commit ID (e.g. 06d1dfe55a5eec2d4b650041cb529f5efdeadd31) from Git;
- complete build log from your compiler and linker, even if it's long (it can always be shortened later, if necessary).

**Comment by sebmavro** [comment]
Sorry, please find some information 
- macbook M1 and macbook  M1 pro -> Apple Silicon Processor
- Operating system macOS BigSur and macOS Monterey (12.0.1)
- makefile generation with cmake version 3.21.4  - Compiler  AppleClang 13.0.0.13000029
- Easy3D v2.4.6
- Log below 
-- Minimum OS X deployment version: 10.12
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Easy3D: I am working on a 64-bit Darwin
-- Found OpenGL: /Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk/System/Library/Frameworks/OpenGL.framework   
-- OpenGL libraries: /Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk/System/Library/Frameworks/OpenGL.framework;/Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk/System/Library/Frameworks/OpenGL.framework
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Using Cocoa for window creation
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Could NOT find OpenMP (missing: OpenMP_C_INCLUDE_DIRS) 
-- Could NOT find OpenMP (missing: OpenMP_C_LIBRARIES) 
-- Could NOT find OpenMP (missing: OpenMP_CXX_INCLUDE_DIRS) 
-- Could NOT find OpenMP (missing: OpenMP_CXX_LIBRARIES) 
-- Found Backward: /Users/mavromatis/Desktop/Easy3D-main/3rd_party/backward  
-- Setting C++11
-- Looking for C++ include execinfo.h
-- Looking for C++ include execinfo.h - found
-- Adding target: easy3d::util (easy3d_util)
-- Adding target: easy3d::core (easy3d_core)
-- Adding target: easy3d::fileio (easy3d_fileio)
-- Adding target: easy3d::kdtree (easy3d_kdtree)
-- Could NOT find Boost (missing: Boost_INCLUDE_DIR) 
-- Adding target: easy3d::algo (easy3d_algo)
-- Adding target: easy3d::renderer (easy3d_renderer)
-- Adding target: easy3d::gui (easy3d_gui)
-- Adding target: easy3d::viewer (easy3d_viewer)
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Could NOT find OpenMP (missing: OpenMP_C_INCLUDE_DIRS) 
-- Could NOT find OpenMP (missing: OpenMP_C_LIBRARIES) 
-- Could NOT find OpenMP (missing: OpenMP_CXX_INCLUDE_DIRS) 
-- Could NOT find OpenMP (missing: OpenMP_CXX_LIBRARIES) 
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Could NOT find OpenMP (missing: OpenMP_C_INCLUDE_DIRS) 
-- Could NOT find OpenMP (missing: OpenMP_C_LIBRARIES) 
-- Could NOT find OpenMP (missing: OpenMP_CXX_INCLUDE_DIRS) 
-- Could NOT find OpenMP (missing: OpenMP_CXX_LIBRARIES) 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mavromatis/Desktop/Easy3D-main/build
mavromatis@MBPdeSebastien build % make
[  0%] Building C object 3rd_party/glew/CMakeFiles/3rd_glew.dir/src/glew.c.o
[  0%] Linking C static library ../../lib/lib3rd_glew.a
[  0%] Built target 3rd_glew
[  0%] Building C object 3rd_party/glfw/src/CMakeFiles/3rd_glfw.dir/context.c.o
[  1%] Building C object 3rd_party/glfw/src/CMakeFiles/3rd_glfw.dir/init.c.o
[  1%] Building C object 3rd_party/glfw/src/CMakeFiles/3rd_glfw.dir/input.c.o
[  1%] Building C object 3rd_party/glfw/src/CMakeFiles/3rd_glfw.dir/monitor.c.o
[  1%] Building C object 3rd_party/glfw/src/CMakeFiles/3rd_glfw.dir/vulkan.c.o
[  2%] Building C object 3rd_party/glfw/src/CMakeFiles/3rd_glfw.dir/window.c.o
[  2%] Building C object 3rd_party/glfw/src/CMakeFiles/3rd_glfw.dir/cocoa_init.m.o
[  2%] Building C object 3rd_party/glfw/src/CMakeFiles/3rd_glfw.dir/cocoa_joystick.m.o
[  3%] Building C object 3rd_party/glfw/src/CMakeFiles/3rd_glfw.dir/cocoa_monitor.m.o
[  3%] Building C object 3rd_party/glfw/src/CMakeFiles/3rd_glfw.dir/cocoa_window.m.o
[  3%] Building C object 3rd_party/glfw/src/CMakeFiles/3rd_glfw.dir/cocoa_time.c.o
[  3%] Building C object 3rd_party/glfw/src/CMakeFiles/3rd_glfw.dir/posix_thread.c.o
[  4%] Building C object 3rd_party/glfw/src/CMakeFiles/3rd_glfw.dir/nsgl_context.m.o
[  4%] Building C object 3rd_party/glfw/src/CMakeFiles/3rd_glfw.dir/egl_context.c.o
[  4%] Building C object 3rd_party/glfw/src/CMakeFiles/3rd_glfw.dir/osmesa_context.c.o
[  4%] Linking C static library ../../../lib/lib3rd_glfw.a
[  4%] Built target 3rd_glfw
[  4%] Building CXX object 3rd_party/imgui/CMakeFiles/3rd_imgui.dir/imgui.cpp.o
[  4%] Building CXX object 3rd_party/imgui/CMakeFiles/3rd_imgui.dir/imgui_demo.cpp.o
[  4%] Building CXX object 3rd_party/imgui/CMakeFiles/3rd_imgui.dir/imgui_draw.cpp.o
[  5%] Building CXX object 3rd_party/imgui/CMakeFiles/3rd_imgui.dir/imgui_widgets.cpp.o
[  5%] Building CXX object 3rd_party/imgui/CMakeFiles/3rd_imgui.dir/imgui_tables.cpp.o
[  5%] Building CXX object 3rd_party/imgui/CMakeFiles/3rd_imgui.dir/backends/imgui_impl_glfw.cpp.o
[  6%] Building CXX object 3rd_party/imgui/CMakeFiles/3rd_imgui.dir/backends/imgui_impl_opengl3.cpp.o
[  6%] Linking CXX static library ../../lib/lib3rd_imgui.a
[  6%] Built target 3rd_imgui
[  6%] Building C object 3rd_party/rply/CMakeFiles/3rd_rply.dir/rply.c.o
[  7%] Linking C static library ../../lib/lib3rd_rply.a
[  7%] Built target 3rd_rply
[  7%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/fopen_compressed.cpp.o
[  8%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/lasfilter.cpp.o
[  8%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/lasreader_asc.cpp.o
[  8%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/lasreader_bil.cpp.o
[  8%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/lasreader_bin.cpp.o
[  9%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/lasreader_dtm.cpp.o
[  9%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/lasreader_las.cpp.o
[  9%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/lasreader_ply.cpp.o
[ 10%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/lasreader_qfit.cpp.o
[ 10%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/lasreader_shp.cpp.o
[ 10%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/lasreader_txt.cpp.o
[ 10%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/lasreader.cpp.o
/Users/mavromatis/Desktop/Easy3D-main/3rd_party/lastools/LASlib/src/lasreader.cpp:1703:11: warning: expression result unused [-Wunused-value]
      if (!add_list_of_files(argv[i+1]), unique)
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
[ 11%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/lasreaderbuffered.cpp.o
[ 11%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/lasreadermerged.cpp.o
[ 11%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/lasreaderpipeon.cpp.o
[ 11%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/lasreaderstored.cpp.o
[ 12%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/lastransform.cpp.o
[ 12%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/lasutility.cpp.o
[ 12%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/laswaveform13reader.cpp.o
[ 13%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/laswaveform13writer.cpp.o
[ 13%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/laswriter_bin.cpp.o
[ 13%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/laswriter_las.cpp.o
[ 13%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/laswriter_qfit.cpp.o
[ 14%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/laswriter_txt.cpp.o
[ 14%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/laswriter_wrl.cpp.o
[ 14%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/laswriter.cpp.o
[ 14%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASlib/src/laswritercompatible.cpp.o
[ 15%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/arithmeticdecoder.cpp.o
[ 15%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/arithmeticencoder.cpp.o
[ 15%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/arithmeticmodel.cpp.o
[ 15%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/integercompressor.cpp.o
[ 16%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/lasindex.cpp.o
[ 16%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/lasinterval.cpp.o
[ 16%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/lasquadtree.cpp.o
[ 17%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/lasreaditemcompressed_v1.cpp.o
[ 17%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/lasreaditemcompressed_v2.cpp.o
[ 17%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/lasreaditemcompressed_v3.cpp.o
[ 17%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/lasreaditemcompressed_v4.cpp.o
[ 18%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/lasreadpoint.cpp.o
[ 18%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/laswriteitemcompressed_v1.cpp.o
[ 18%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/laswriteitemcompressed_v2.cpp.o
[ 18%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/laswriteitemcompressed_v3.cpp.o
[ 19%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/laswriteitemcompressed_v4.cpp.o
[ 19%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/laswritepoint.cpp.o
[ 19%] Building CXX object 3rd_party/lastools/CMakeFiles/3rd_lastools.dir/LASzip/src/laszip.cpp.o
[ 20%] Linking CXX static library ../../lib/lib3rd_lastools.a
[ 20%] Built target 3rd_lastools
[ 20%] Building CXX object 3rd_party/kdtree/CMakeFiles/3rd_kdtree.dir/ANN/ANN.cpp.o
[ 20%] Building CXX object 3rd_party/kdtree/CMakeFiles/3rd_kdtree.dir/ANN/bd_fix_rad_search.cpp.o
[ 21%] Building CXX object 3rd_party/kdtree/CMakeFiles/3rd_kdtree.dir/ANN/bd_pr_search.cpp.o
[ 21%] Building CXX object 3rd_party/kdtree/CMakeFiles/3rd_kdtree.dir/ANN/bd_search.cpp.o
[ 21%] Building CXX object 3rd_party/kdtree/CMakeFiles/3rd_kdtree.dir/ANN/bd_tree.cpp.o
[ 21%] Building CXX object 3rd_party/kdtree/CMakeFiles/3rd_kdtree.dir/ANN/brute.cpp.o
[ 22%] Building CXX object 3rd_party/kdtree/CMakeFiles/3rd_kdtree.dir/ANN/kd_dump.cpp.o
[ 22%] Building CXX object 3rd_party/kdtree/CMakeFiles/3rd_kdtree.dir/ANN/kd_fix_rad_search.cpp.o
[ 22%] Building CXX object 3rd_party/kdtree/CMakeFiles/3rd_kdtree.dir/ANN/kd_pr_search.cpp.o
[ 23%] Building CXX object 3rd_party/kdtree/CMakeFiles/3rd_kdtree.dir/ANN/kd_search.cpp.o
[ 23%] Building CXX object 3rd_party/kdtree/CMakeFiles/3rd_kdtree.dir/ANN/kd_split.cpp.o
[ 23%] Building CXX object 3rd_party/kdtree/CMakeFiles/3rd_kdtree.dir/ANN/kd_tree.cpp.o
[ 23%] Building CXX object 3rd_party/kdtree/CMakeFiles/3rd_kdtree.dir/ANN/kd_util.cpp.o
[ 24%] Building CXX object 3rd_party/kdtree/CMakeFiles/3rd_kdtree.dir/ANN/perf.cpp.o
[ 24%] Building CXX object 3rd_party/kdtree/CMakeFiles/3rd_kdtree.dir/ETH_Kd_Tree/kdTree.cpp.o
[ 24%] Linking CXX static library ../../lib/lib3rd_kdtree.a
[ 24%] Built target 3rd_kdtree
[ 24%] Building CXX object 3rd_party/ransac/CMakeFiles/3rd_ransac.dir/Bitmap.cpp.o
In file included from /Users/mavromatis/Desktop/Easy3D-main/3rd_party/ransac/Bitmap.cpp:1:
In file included from /Users/mavromatis/Desktop/Easy3D-main/3rd_party/ransac/Bitmap.h:3:
In file included from /Users/mavromatis/Desktop/Easy3D-main/3rd_party/ransac/MiscLib/Vector.h:3:
In file included from /Users/mavromatis/Desktop/Easy3D-main/3rd_party/ransac/MiscLib/AlignedAllocator.h:9:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/xmmintrin.h:13:
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:33:5: error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?
    __builtin_ia32_emms();
    ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:33:5: note: '__builtin_isless' declared here
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:33:25: error: too few arguments to function call, expected 2, have 0
    __builtin_ia32_emms();
    ~~~~~~~~~~~~~~~~~~~~^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:50:19: error: use of undeclared identifier '__builtin_ia32_vec_init_v2si'
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:67:12: error: use of undeclared identifier '__builtin_ia32_vec_ext_v2si'
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
           ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:129:19: error: use of undeclared identifier '__builtin_ia32_packsswb'
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:159:19: error: use of undeclared identifier '__builtin_ia32_packssdw'
    return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:189:19: error: use of undeclared identifier '__builtin_ia32_packuswb'
    return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:216:19: error: use of undeclared identifier '__builtin_ia32_punpckhbw'
    return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:239:19: error: use of undeclared identifier '__builtin_ia32_punpckhwd'
    return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:260:19: error: use of undeclared identifier '__builtin_ia32_punpckhdq'
    return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:287:19: error: use of undeclared identifier '__builtin_ia32_punpcklbw'
    return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:310:19: error: use of undeclared identifier '__builtin_ia32_punpcklwd'
    return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:331:19: error: use of undeclared identifier '__builtin_ia32_punpckldq'
    return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:352:19: error: use of undeclared identifier '__builtin_ia32_paddb'; did you mean '__builtin_arm_addg'?
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:352:19: note: '__builtin_arm_addg' declared here
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:352:19: error: first argument of MTE builtin function must be a pointer ('__v8qi' (vector of 8 'char' values) invalid)
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                  ^                    ~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:373:19: error: use of undeclared identifier '__builtin_ia32_paddw'; did you mean '__builtin_arm_addg'?
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:352:19: note: '__builtin_arm_addg' declared here
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:373:19: error: first argument of MTE builtin function must be a pointer ('__v4hi' (vector of 4 'short' values) invalid)
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
                  ^                    ~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:394:19: error: use of undeclared identifier '__builtin_ia32_paddd'; did you mean '__builtin_arm_addg'?
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:352:19: note: '__builtin_arm_addg' declared here
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:394:19: error: first argument of MTE builtin function must be a pointer ('__v2si' (vector of 2 'int' values) invalid)
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
                  ^                    ~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [3rd_party/ransac/CMakeFiles/3rd_ransac.dir/Bitmap.cpp.o] Error 1
make[1]: *** [3rd_party/ransac/CMakeFiles/3rd_ransac.dir/all] Error 2
make: *** [all] Error 2

That's all ! Thanks for your reply.

**Comment by LiangliangNan** [comment]
I’ve pushed some changes to the “dev” branch and the code now passed the test on a friend’s laptop (I myself don’t have the new MacBook).
Can you please give a try and let me know if it works?

**Comment by sebmavro** [comment]
It just works! Thank you.

**Comment by LiangliangNan** [comment]
Glad to hear that. Then I close this issue now. 
Thanks and good luck!
