### ISSUE TITLE
Tutorial_311_Animation crash.

### ISSUE THREAD

**Issue by Davar1990** [LiangliangNan/Easy3D#102]
Hello again, 

I have an application in which I have a surface mesh whose vertices are constantly updated in real time. Since the Viewer::run() function isn't virtual, I don't know how to feed the updates to the viewer such that the same viewer window can display the changes without having to terminate and getting reinitialized from scratch. I tried to look into the animation example provided by the library. Firstly, I don't think that tutorial is the answer to my problem as my application should go beyond the Viewer::run() function to make the updates on vertices followed by the normals. Second, I wanted to bring this to your attention that this particular example actually crashes upon execution. Please find the details in the screenshot below. 

![Capture](https://user-images.githubusercontent.com/17028943/146068927-a9733970-76f9-4f11-89d2-52df7a66dbde.PNG)

I also tried to accomplish the desired outcome by running the Viewer::run() function on a separate thread as `std::thread t1(&Viewer::run, &viewer)` but it didn't work. I would appreciate any suggestions.

**Comment by LiangliangNan** [comment]
Hi, thanks for reporting this issue and I will investigate in detail (I need to borrow a Windows machine).

How big is your data (the number of vertices and normals to be sent to GPU)?

The crash might be due to that the update is carried more frequently than the process capability of your CPU/GPU/RAM, i.e., the GPU receives new data but the last update has not been completed yet.

I am not 100% sure, but this could be verified by simply modifying the current update frequency, at line 1025 in `easy3d/viewer/viewer.cpp`:
`  static const int animation_fps = 30;`
You can change the expected fps to 5 (for example) and run again. 
If it still crashes, then I think it is necessary to set a barrier for data transfer between CPU and GPU.

Another way for this is to keep a pointer of the drawable and update the relevant buffers (vertex, normal, ...) when you need to update the rendering.

Be careful with multi-threading: the current examples use GLFW for constructing the views, and the accessing/writing OpenGL resources can ONLY be done from the main thread (i.e., the thread where the OpenGL context was created).

**Comment by Davar1990** [comment]
I just pulled the recent changes, rebuilt the library and the tutorial example is working fine now. Thanks for the quick fix and for the tips. I'm going to look into the animation example more carefully now to see if I can use it for my real time application.

**Comment by LiangliangNan** [comment]
This example shows how to update the vertex buffer when the vertex positions have changed. 
But how an animation can be generated is another topic that is not covered in Easy3D.

If you would like to have walk though (i.e., moving the camera to explore a scene), the camera interpolation example is more relevant.
But I guess the former is what needed in you work. Good luck with your research!

**Comment by Davar1990** [comment]
Thanks for your good luck wish. I spent quality time on this and made so much progress, as far as I could. Now I have hit a wall and I could really use your kind help. 
Basically, I created a `CustomViewer` class inheriting from the viewer class and added customized functions to simulate `Viwer::run()` . My goal is to animate the facial expressions of a 3D face mesh. In order to test my implementation, I tried switching back and forth between two expressions (open/closed mouth). The code is as follows and it runs successfully. 

```
CustomViewer viewer("mesh animation");
viewer.set_background_color(easy3d::vec4(0.6, 0.8, 0.8, 0.1));
easy3d::Camera* cam = viewer.camera();
cam->setUpVector(easy3d::vec3(0, 1, 0));
cam->setViewDirection(easy3d::vec3(0, 0, -1));

auto surface = new easy3d::TrianglesDrawable("faces");
surface->update_vertex_buffer(face1);
surface->update_element_buffer(indices);
surface->set_uniform_coloring(easy3d::vec4(0.8, 0.8, 0.8, 1.0));
viewer.add_drawable(surface);

viewer.initialize();
GLFWwindow* window = viewer.getWindow();

while (true) {

	//=============== face 1 (closed mouth)
	surface->update_vertex_buffer(face1);
	viewer.custom_draw();
	glfwSwapBuffers(window);
	std::this_thread::sleep_for(std::chrono::milliseconds(static_cast<int>(200)));

	//=============== face 2 (open mouth)
	surface->update_vertex_buffer(face2);
	viewer.custom_draw();
	glfwSwapBuffers(window);
	std::this_thread::sleep_for(std::chrono::milliseconds(static_cast<int>(200)));

	glfwPollEvents();

	if (glfwWindowShouldClose(window) || viewer.should_exit()) {
		viewer.custom_cleanup();
		break;
	}

}

glfwTerminate();
return EXIT_SUCCESS;
```
My facial mesh has quads not triangles but I transformed the indices for triangles by rearranging them as `v0, v1, v2, v2, v3, v0`.

Here's the result
https://drive.google.com/file/d/19h8W-mqHV2GZhNI704I3sjcPZVjiOi7d/view?usp=sharing

But my end goal is to achieve the same with smooth surface for which I'm building the `SurfaceMesh` with QUADS, not triangles as follows.

```
easy3d::SurfaceMesh* mesh = new easy3d::SurfaceMesh();
vector<easy3d::SurfaceMesh::Vertex> surfaceVertices(face1.size());
for (int i = 0; i < face1.size(); i++)
	surfaceVertices[i] = mesh->add_vertex(face1[i]);
for (int i = 0; i < _quads.size(); i++) {
	mesh->add_quad(
		surfaceVertices[_quads[i][0]], 
		surfaceVertices[_quads[i][1]], 
		surfaceVertices[_quads[i][2]], 
		surfaceVertices[_quads[i][3]]);
}
viewer.add_model(mesh);        
auto surface = mesh->renderer()->get_triangles_drawable("faces");  
surface->set_smooth_shading(true);
surface->set_uniform_coloring(easy3d::vec4(0.8, 0.8, 0.8, 1.0));
```
![smooth_shade](https://user-images.githubusercontent.com/17028943/146320844-4bd8b64f-6157-49ad-a3dd-9ecdbf85162e.PNG)

So in the original implementation, I replaced the following section by the one above and ran the animation again. 

```
auto surface = new easy3d::TrianglesDrawable("faces");
surface->update_vertex_buffer(face1);
surface->update_element_buffer(indices);
surface->set_uniform_coloring(easy3d::vec4(0.8, 0.8, 0.8, 1.0));
viewer.add_drawable(surface);
```
First I tried `surface->set_smooth_shading(true);`
https://drive.google.com/file/d/1yI1gz74lL2NAqS1bB4CxnLQPITIBtC9G/view?usp=sharing

Then I tried `surface->set_smooth_shading(false);`
https://drive.google.com/file/d/1kAhxA-1Hs-ZxJYC3Qw9Dw5rD05I9CCGj/view?usp=sharing

Even though I can compute the normals myself, it would be ideal if I could achieve the end goal leaving the normals computation up to the library itself. I tried my best to figure out how I could fix this issue but now I feel I have hit a wall. I would very much appreciate your help.
