### ISSUE TITLE
[Question] how to convert obj file to point cloud file without rendering?

### ISSUE THREAD

**Issue by ccworld1000** [LiangliangNan/Easy3D#103]
[Question] how to convert obj file to point cloud file without rendering?

**Comment by LiangliangNan** [comment]
I don't quite get your question. An obj file usually store a mesh, do you mean
  - export only the vertices of the mesh and visualize them, or
  - sample the surfaces of the mesh as a point cloud, and then visualize it?

**Comment by ccworld1000** [comment]
yes

**Comment by ccworld1000** [comment]
More data points may have a good effect, but less data points may have no effect. The premise is that first I have to convert the model into a point cloud, and then display it. It feels that E3D almost realizes this function. I don't seem to see the obvious interface, or I have such questions.

**Comment by ccworld1000** [comment]
There are two layers, as you mentioned above
1. When there are many data points, only the points are exported for virtualization display, and the display effect may be good.
2 when there are few data points, increase sampling to make it look more in line with its shape.

Scenario 1: I feel that the existing framework may be able to do it directly.
Scenario 2: if it is very complex, ignore it.

**Comment by LiangliangNan** [comment]
Now I managed to understand your need. Indeed, exporting the vertices is quite simple: you only need to traverse all the vertices and write the XYZ coordinates into a file.
To sample the surface of a mesh, you can use the `SurfaceMeshSampler` class in `easy3d/algo/surface_mesh_sampler.h` (see below the API)

<img width="881" alt="Screen Shot 2021-12-15 at 14 10 30" src="https://user-images.githubusercontent.com/15526536/146192420-3a0d76e0-d578-400c-92d5-738668a92616.png">

**Comment by ccworld1000** [comment]
还是用中文描述吧，英文翻译滴感觉老是不到位！

问题1 : 上面采用时间上有啥好办法优化或者改善,提升？[主要执行时间速度，好比放在一个实时环境中，可能涉及不止这一个环节的处理]

问题2：如果不局限于顶点数据，加入其他的考虑，好比保留颜色等，以前对应存取

问题3：可能分2部分
问题3.1:  封闭空间，不仅仅采样到表面，可以让其采样到空间内部.
问题3.2: 非封闭空间，这个就麻烦，如果从视角上看出现遮挡，遮挡部分滴不采样，如果可以做开关切换会更好

**Comment by ccworld1000** [comment]
[color_cube.zip](https://github.com/LiangliangNan/Easy3D/files/7724077/color_cube.zip)
这里导了一个立方体模型

**Comment by LiangliangNan** [comment]
See my answers below:

> 问题1 : 上面采用时间上有啥好办法优化或者改善,提升？[主要执行时间速度，好比放在一个实时环境中，可能涉及不止这一个环节的处理]

错别字“采用” -> "采样" :-(
Short answer: 我不知道。因为我不清楚你要做什么样的采样，什么目的，什么程度，什么精度才满足你的要求。
An idea that may work (100% for convex objects) : 你可以将模型在不同视角渲染，然后提取depth buffer，将这些depth images转换集成到一个点云。这些都可以在GPU里面用shader实现，几百万的采样点达到实时应该不是问题。

> 问题2：如果不局限于顶点数据，加入其他的考虑，好比保留颜色等，以前对应存取
取决于什么颜色，比如面片的颜色（或者来自texture），采样点来自哪个面片，就保留那个面片的颜色。如果是别的比如标量场，那就看那采样点对应的标量场的数值，找到对应的颜色付给它即可。

> 问题3：可能分2部分 问题3.1: 封闭空间，不仅仅采样到表面，可以让其采样到空间内部. 问题3.2: 非封闭空间，这个就麻烦，如果从视角上看出现遮挡，遮挡部分滴不采样，如果可以做开关切换会更好
没看懂 “遮挡部分滴不采样” :-(
如果对物体内部空间采样，你可以将整个三维空间（局现在物体包围盒内）做格子状划分，然后判断哪些格子点落在模型内即可。
如果模型不封闭，那就没有100%的把握，只能在一定概率上判断一个点是否在模型内部。


我想你的这些问题已经超出了Easy3D的使用或者issue的覆盖面了。抱歉！

为了更有效地解决问题，我建议这个：
http://catb.org/~esr/faqs/smart-questions.html
其中有一条：Choose your forum carefully （在对的地方问对的人），希望有帮助！

Good luck with your research!

**Comment by ccworld1000** [comment]
输入联想敲成常用滴频率词汇，主要去想问题去啦，对是采样，非常抱歉！

**Comment by ccworld1000** [comment]
`
int main (int argc, char **argv) {
  // color_cube_000001.obj 输入模型, output_sampling_N.xyz 输出模型, 采样点数
  surfaceMeshSampling("color_cube_000001.obj", "output_sampling_1.xyz", 10000);
  surfaceMeshSampling("color_cube_000001.obj", "output_sampling_2.xyz", 50000);
  surfaceMeshSampling("color_cube_000001.obj", "output_sampling_3.xyz", 100000);

  return 0;
}
`

**Comment by ccworld1000** [comment]
CC # ./CCTest
2021-12-16 17:54:51,179 INFO [default] surface mesh loaded (#face: 6, #vertex: 8, #edge: 12). 0.6ms
mesh loaded.
2021-12-16 17:54:51,180 WARNING [default] this is not a triangle mesh (creating a temporary triangle mesh by triangulating the input...)
2021-12-16 17:54:51,180 INFO [default] sampling surface...
2021-12-16 17:54:51,186 INFO [default] done. resulted point cloud has 10000 points
2021-12-16 17:54:51,301 INFO [default] save model done. 115.4ms
Test for input file : color_cube_000001.obj, Sampling points: 10000, output filename output_sampling_1.xyz
2021-12-16 17:54:51,302 INFO [default] surface mesh loaded (#face: 6, #vertex: 8, #edge: 12). 0.3ms
mesh loaded.
2021-12-16 17:54:51,302 WARNING [default] this is not a triangle mesh (creating a temporary triangle mesh by triangulating the input...)
2021-12-16 17:54:51,302 INFO [default] sampling surface...
2021-12-16 17:54:51,323 INFO [default] done. resulted point cloud has 50000 points
2021-12-16 17:54:51,767 INFO [default] save model done. 443.9ms
Test for input file : color_cube_000001.obj, Sampling points: 50000, output filename output_sampling_2.xyz
2021-12-16 17:54:51,769 INFO [default] surface mesh loaded (#face: 6, #vertex: 8, #edge: 12). 0.4ms
mesh loaded.
2021-12-16 17:54:51,769 WARNING [default] this is not a triangle mesh (creating a temporary triangle mesh by triangulating the input...)
2021-12-16 17:54:51,769 INFO [default] sampling surface...
2021-12-16 17:54:51,816 INFO [default] done. resulted point cloud has 100000 points
2021-12-16 17:54:52,793 INFO [default] save model done. 977.2ms
Test for input file : color_cube_000001.obj, Sampling points: 100000, output filename output_sampling_3.xyz
CC #

**Comment by ccworld1000** [comment]
save model done 对应时间用粗体+斜体 标识，这个是框架内部打印出来。
十万点采样保存大概1秒，应用场景有可能是实时渲染中obj中转ply，这个存取时间上是否还有优化改进。

**Comment by ccworld1000** [comment]
save model done 对应时间用粗体+斜体 标识，这个是框架内部打印出来。
十万点采样保存大概1秒，应用场景有可能是实时渲染中obj中转ply，这个存取时间上是否还有优化改进。

**Comment by ccworld1000** [comment]
超出范畴问题直接忽略就好

**Comment by LiangliangNan** [comment]
> save model done 对应时间用粗体+斜体 标识，这个是框架内部打印出来。 十万点采样保存大概1秒，应用场景有可能是实时渲染中obj中转ply，这个存取时间上是否还有优化改进。

这个是“保存”（写数据到磁盘）的时间。xyz是ASCII格式，所以慢。
你可以用**二进制**的 ply 或者 bin 格式，这两个要快很多。
但是不管多快，磁盘IO总是有上限的，能否做到实时取决于采样点个数。你也可以用内存映射，再创建一个buffer，等数据积攒到一定程度（例如1G），然后统一保存到磁盘。当然，这需要写些代码实现。

**Comment by ccworld1000** [comment]
这用滴是闪盘速度应该快些，机械硬盘估计就没那么快啦！
其他格式颜色好像也会丢失，期望的格式obj，之前尝试直接导入obj只有点数据到app，好像显示不了，就直接把模型删了，可能正常思维不这样做吧。
