### ISSUE TITLE
[PointSetIO] Error: reading file failed (no data exist)

### ISSUE THREAD

**Issue by TalonX1** [LiangliangNan/Easy3D#105]
when I try to use the mapple(old single version on your website),I can not open point cloud file，and get the above information.

[unregular_building.zip](https://github.com/LiangliangNan/Easy3D/files/7755212/unregular_building.zip)

**Comment by LiangliangNan** [comment]
I am not quite sure which version of Mapple did you use :-(
Make sure every line has 3 coordinates separated by space (no commas, no other characters accepted).

That Mapple on with website (which is Windows only) is not maintained anymore. You may want to use the new version (which is a demo of Easy3D):
https://github.com/LiangliangNan/Easy3D/releases

**Comment by TalonX1** [comment]
I think I have found the reason.There is chinese in the file path.Thank you,doctor.

**Comment by Ryanzovey1** [comment]
> 我觉得我找到原因了，文件路径里有中文，谢谢医生。

感谢，问题解决了，早知道还是遇事不决改英文路径哈哈：>
