### ISSUE TITLE
how I can color the lines in the PointCloud Class

### ISSUE THREAD

**Issue by jinshuguangze** [LiangliangNan/Easy3D#106]
Hello,I aim to get the feature lines in PointCloud,so I need color them so I can distinguish them.But it seems that the PointCloud Class has no property to color lines.
So if I tranform the PointCloud to SurfaceMesh and color these lines,will it success?

**Comment by LiangliangNan** [comment]
Point clouds are just unorganized points, and there are no lines in a point cloud representation. From your question, it is not clear what lines you meant.

Anyway, I assume you have a set of lines to visualize, which can be simply achieved in the following steps:
 - create a LinesDrawable. 
 - feed the drawable with the coordinates of the endpoints of the lines.
 - set the properties of the lines (e.g., draw as plain lines or cylinders, color).

Check 'Tutorial_301_Drawables', 'Tutorial_304_VectorField', and 'Tutorial_302_Imposters' for examples.
