### ISSUE TITLE
Request: thick arc primitive

### ISSUE THREAD

**Issue by coolbix** [LiangliangNan/Easy3D#107]
Could you please kindly add a primitive to creat a "thick" arc or circle something like "create_thick_arc()"?
Thank you.

**Comment by LiangliangNan** [comment]
I don't get your question. I have multiple interpretations. "primitive" refers to the very fundamental element in rendering (such as points, line segments, or triangles), or commonly seen basic geometric types (like spheres, cylinders, planes, etc).
 - Is it a 2D shape, or a 3D shape?   
 - Is it for detecting such a shape from point clouds, or just for rendering?
In any case, I won't call it primitive.  

Besides, why it is necessary for Easy3D?  To what extent it is useful for Easy3D users? If this is just for a very particular rendering purpose, then it seems there is no sufficient motivation to introduce it to Easy3D.

**Comment by coolbix** [comment]
Ok got it. I'm going to retract my request.
Thanks for the reply.
