### ISSUE TITLE
Edges highlight 

### ISSUE THREAD

**Issue by yidahuang** [LiangliangNan/Easy3D#109]
Hi Liangliang,
I found an issue with edges highlight rendering. It looks like this function doesn't work. Could you please check it?
![image](https://user-images.githubusercontent.com/18398235/152977967-fdd9a020-56c6-461d-827d-4d5c93306b65.png)

**Comment by LiangliangNan** [comment]
Now Mapple supports highlighting a range of line segments (specified by the min and max indices of the edges).
A known limitation of current implementation: effective only in plain rendering mode and for lines with a width of 1.
