### ISSUE TITLE
I/O update : PLY format for colored points cloud

### ISSUE THREAD

**Issue by sebmavro** [LiangliangNan/Easy3D#112]
Hello, I am currently working on colored points cloud (x, y, z and r, b, g information for each vertex).  The PLY format allows to save the colors coded on 8 bits (unsigned char) but it seems that Easy3D color property must be of type "float". Am I right?
If this is the case, it is annoying because the files are not compatible with software such as MeshLb for exemple ...
Is there a way to fix this quickly ?
Have a nice day.
Best Regards.

**Comment by LiangliangNan** [comment]
In PLY format, it can be either **unsigned char** or **float**. Easy3D can load both, but it saves **float** (by default) to files.
Did you mean that MeshLab cannot load **float** type color?
I can also change the default behavior of Easy3D to use **unsigned char**.

**Comment by sebmavro** [comment]
That's it : I think It should be better to save unsigned char by default.
MeshLab shows black points with float type colors.
I saved the points cloud from "Tutorial_102_PointCloud_Property" (random color) on PLY format. Please find a screen capture attached ... not so nice :-(.
<img width="511" alt="Capture d’écran 2022-03-03 à 10 49 27" src="https://user-images.githubusercontent.com/5520076/156539859-24e63dec-3b2c-407b-a587-7a4cd850cd61.png">

**Comment by sebmavro** [comment]
It looks very nice ! I understand that float type can be used in PLY format. 
I really think that this default behavior (uchar) is better.
Thank you for your really fast changes.
Best regards.
<img width="377" alt="Capture d’écran 2022-03-03 à 12 05 25" src="https://user-images.githubusercontent.com/5520076/156553194-2be73df7-7f11-4aa7-906e-31244acdb3ae.png">

**Comment by LiangliangNan** [comment]
Thanks for the suggestion. Now the changes are also in the **main** branch.
Good luck with your research!
