### ISSUE TITLE
Corner of the Window

### ISSUE THREAD

**Issue by petrasvestartas** [LiangliangNan/Easy3D#115]
Hi,

I have another question. Is it possible to define the corner of the window?
I can change the viewer width and size, but the window itself appears on a random position of the screen.
Is it possible to set it up for example at the top left of my monitor?

![image](https://user-images.githubusercontent.com/18013985/163591955-2b6a0ec9-9909-40f3-b21d-eb5806ee6875.png)

**Comment by LiangliangNan** [comment]
I've just added such a member function to the `Viewer` class:
```C++
        /**
         * @brief Sets the position of the content area of the viewer.
         * @details This function sets the position, in screen coordinates, of the upper-left corner of the content
         *      area of the viewer. If the viewer is a full screen window, this function does nothing.
         *  @param xpos The x-coordinate of the upper-left corner of the content area.
         *  @param ypos The y-coordinate of the upper-left corner of the content area.
         *  @note This function must only be called from the main thread.
         */
        void set_position(int xpos, int ypos);
```

You can called it like
```C++
        viewer.set_position(100, 100);
```

**Comment by petrasvestartas** [comment]
Thank you, I will download the new version.
