### ISSUE TITLE
Projecting 2d pixel to 3d mesh and creating texture 

### ISSUE THREAD

**Issue by utkarshkulkarni15** [LiangliangNan/Easy3D#117]
I am working on problem of mapping 2d pixel to 3d vertex on mesh. I have parameters for this like camera intrinsic and extrinsic matrix. 
I need to project 3d mesh on 2d image and replace mapped pixels with single  color and create texture from that and render in quad.
Can you please suggest how I can proceed on this in easy3d.  Means i need to replace part of mapped 2d locations in existing 2d images texture with one color. It will be grateful if your suggest direction on this. I followed Real camera tutorial for projecting view using camera parameters.

**Comment by LiangliangNan** [comment]
From 3D -> 2D, we have `p = K [R, t] * P`, where `K` is the intrinsic camera matrix, `R` is rotation `t` is translation.
When projecting from 2D to 3D, a pixel will be mapped to a ray. 
In the camera coordinate system, we have the 3D point`P = K^-1 * p`.
Converting it to the world coordinate system, we get `P = R^-1 * (K^-1 * p - t)`.
Then the ray is from the camera's position (can be obtained using `camera->position()`) pointing to this point.

**Comment by utkarshkulkarni15** [comment]
Hi ,
Thanks for replying immediately.
That's really great. Thanks for sharing code. It will be really helpful to us.   
For more insight , I am adding more details what we want to achieve final output using 2d to 3d or 3d to 2d mapping as below:
We have 3d mesh model of face which we want to project on 2d image so that we can get below output:

Below is 3d mesh
![image](https://user-images.githubusercontent.com/103943132/166667726-6d93065a-fb2a-4bca-8b6d-e4c1a91f6bdf.png)

Below is overlayed 2d projection of mesh on 2d face
![image](https://user-images.githubusercontent.com/103943132/166666630-510ae080-2914-4707-a8b9-f933a51447e7.png)

In above image face pixels in 2d image are  overlayed by mapping 3d vertices of mesh and replacing color. 
If we map 3d to 2d projection using using above formula p = K [R, t] * P  it will be sparse. So it will not fill all pixels of face.
Instead if we do 2d to 3d we can get ray hit to 3d and if it is valid we can replace color.

We are trying to create texture of 2d image with original face and then replace face pixels by mapping to 3d.Should we use blending of textures. How we can access individual pixels in easy3d for replacing its color.

If you can give  valuable suggestion or comments on our approach and how we can do it in easy3d  it will really help us.

**Comment by LiangliangNan** [comment]
You can use `p = K [R, t] * P` to project the 3D vertices of the mesh onto the image. Then the corresponding image points define the texture coordinates of the 3D vertices.
Using texture mapping, you can *paint* the interior of each triangle face with the color linear interpolated from the image.

**Comment by LiangliangNan** [comment]
I believe the issue has been solved, so I am closing it now.
Feel free to reopen it if this is not the case.
Good luck with your project!

**Comment by utkarshkulkarni15** [comment]
Really sorry for late reply. Currently I am implementing  solution you suggested  using texture mapping for filling triangles using texture coordinates.  I will let you know how it goes. Meantime you can close this issue. Will update on this. If anything will revert back to you.
