### ISSUE TITLE
Is there a raycasting example? I want to simulate a Lidar

### ISSUE THREAD

**Issue by qpc001** [LiangliangNan/Easy3D#118]

**Comment by LiangliangNan** [comment]
I've just added a virtual scanner example in `Tutorial_404_VirtualScanner`.
Everything visible (and only those) will be captured in one shot. It currently doesn't allow any noise.
If you run this example and you will immediately see how it works.
Let me know if you have any suggestions/ideas to improve it.

**Comment by LiangliangNan** [comment]
I believe the issue has been solved, so I am closing it now.
Feel free to reopen it if this is not the case.
Good luck with your project!
