### ISSUE TITLE
Drawables set color

### ISSUE THREAD

**Issue by petrasvestartas** [LiangliangNan/Easy3D#125]
Hi,

I am using example a basic example to load a 3d model.
By default the loaded model is orange, how you would change the color of mesh faces to default grey color?
Also is there a way to hide 3D axis in the viewer in code not by keyboard?

```cpp
    ViewerImGui viewer("viewer_imgui");
    viewer.set_background_color(vec4(1, 1, 1, 1));

    if (!viewer.add_model(file_name))
    {
        LOG(ERROR) << "Error: failed to load model. Please make sure the file exists and format is correct.";
        return EXIT_FAILURE;
    }
```

![image](https://user-images.githubusercontent.com/18013985/175900746-f5c5b64d-f675-4545-a502-ca02f184ab96.png)

**Comment by LiangliangNan** [comment]
> I am using example a basic example to load a 3d model. By default the loaded model is orange, how you would change the color of mesh faces to default grey color? Also is there a way to hide 3D axis in the viewer in code not by keyboard?

You might have noticed that the `Drawable` inherits from `[State](https://github.com/LiangliangNan/Easy3D/blob/7eb439e7b4526edaaa47004e9c563741d61ad53c/easy3d/renderer/state.h#L45)'. `State' provides a set of functions that controls the rendering states of a drawable.  Check the State header file for more details.

To hide the 3D axis in the viewer, you can call `drawable_axes_->set_visible(false)` in your subclass of the viewer, where `drawable_axes_` is a protected member.

**Comment by petrasvestartas** [comment]
First Question:

before I was doing this, to set uniform color, but how do you write code to drawable that are already added to the viewer?

```cpp
    drawable->set_uniform_coloring(easy3d::vec4(0.0f, 0.0f, 0.0f, 1.0f));
    viewer.add_drawable(drawable);
```

second question

If I add this line, the compiler produces the error, any idea why?
```
error C2027: use of 
undefined type 'easy3d::TrianglesDrawable'
```

![image](https://user-images.githubusercontent.com/18013985/175919530-ff8913ec-2c59-4854-b719-7031a00c7434.png)

**Comment by LiangliangNan** [comment]
For 1st Q: 
one can call  `drawable->set_uniform_coloring(...)` anywhere after the model has been loaded to change the color of its drawables.

For 2nd Q: 
include the header file, i.e.,`#include <easy3d/renderer/drawable_triangles.h>'.

Some general suggestions: 
- please check/try the provided functions before you raise a question here.
- many issues related to programming (e.g., the compiling error) can be easily solved by googling. Here I will only reply to issues related to Easy3D.
