### ISSUE TITLE
How Easy3D renders lines?

### ISSUE THREAD

**Issue by petrasvestartas** [LiangliangNan/Easy3D#129]
Hi,

How Easy3D renders 3D lines (no code needed just explanation of implementation concept)?
Is it actually a list of 3d cylinders that are oriented using transformation matrix in shaders?

If cylinders are 3D do you use the concept of instancing of something more simple? I am trying to learn opengl myself. By instancing I mean this: https://learnopengl.com/Advanced-OpenGL/Instancing

**Comment by LiangliangNan** [comment]
The rendering of 3D lines as cylinders in Easy3D is based on [Geometry Shader](https://www.khronos.org/opengl/wiki/Geometry_Shader).
In the geometry shader, new vertices are generated to create the geometry of the cylinder. They are sent to the fragment shader to produce visually *perfect* cylinders.
The implementation can be found in the following shader files:
https://github.com/LiangliangNan/Easy3D/blob/main/resources/shaders/lines/lines_cylinders_color.vert
https://github.com/LiangliangNan/Easy3D/blob/main/resources/shaders/lines/lines_cylinders_color.geom
https://github.com/LiangliangNan/Easy3D/blob/main/resources/shaders/lines/lines_cylinders_color.frag

I hope this helps!

**Comment by petrasvestartas** [comment]
I only new vertex and and fragment shander. I was not aware of geomertry shader. Thank you. 
Seems I have a lot to learn...

Do yoų use 6 vertices per cylinder, 3 for bottom and 3 for top?

**Comment by LiangliangNan** [comment]
> Do you use 6 vertices per cylinder, 3 for bottom and 3 for top?
Yes. You can find the implementation in the geometry shader.

**Comment by petrasvestartas** [comment]
For geometry shaders, how many 3D lines can you maximum render?

During your implementation did you follow the standard pattern like the one bellow? Or there is a smarter way to render large amount of objects?
```

	glGenVertexArrays(1, &vao);
	glBindVertexArray(vao);

	GLuint vbo;
	glGenBuffers(1, &vbo);
	glBindBuffer(GL_ARRAY_BUFFER, vbo);
	glBufferData(GL_ARRAY_BUFFER, vertices.size() * sizeof(glm::vec3), glm::value_ptr(vertices[0]), GL_STATIC_DRAW);
	glEnableVertexAttribArray(0);
	glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 0, nullptr);

	GLuint ibo;
	glGenBuffers(1, &ibo);
	glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, ibo);
	glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.size() * sizeof(glm::uvec4), glm::value_ptr(indices[0]), GL_STATIC_DRAW);

	glBindVertexArray(0);
	glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0);
	glBindBuffer(GL_ARRAY_BUFFER, 0);
```

**Comment by LiangliangNan** [comment]
Yes. The easy3d implementation also follows the standard pattern as shown in your code.
In general, it tries to minimize the OpenGL calls (i.e., transfer data to GPU once, and when drawing only calls the necessary glBind... and glDraw... functions.

I believe there is no bug or actual issue with the code of Easy3D, so I am going to close this issue. Feel free to re-open if encounter any such issues.

**Comment by petrasvestartas** [comment]
Thank you for the explanations
