### ISSUE TITLE
Problem with image export

### ISSUE THREAD

**Issue by boomberung** [LiangliangNan/Easy3D#13]
Hello, can i import mesh as .obj file and export as image? Dont find this opportunity in tutorials.

**Comment by LiangliangNan** [comment]
Did you mean a snapshot of the rendering? If so, after you load the model to the viewer, press the "s" key and you will see the dialog for the snapshot. You can press F1 to see the manual.

**Comment by boomberung** [comment]
@LiangliangNan Thank you for answer, but i need to do snapshot automaticaly for many 3d meshes, so i cant press "s" every time. Is it possible? (I mean i need load 100 3d meshes (.obj files) in viewer and take 100 images (.png files))

**Comment by LiangliangNan** [comment]
Yes. It is easy. Please have a look at the following function in viewer.cpp (line 1184):
    `bool Viewer::snapshot(bool bk_white /* = true*/) const;  `
You can simply modify or add a similar function that takes the file name as input. The difference is that you remove the code that pops up the file dialog.
Every time when a new model is loaded, call the update() function to update the rendering before you call your snapshot function.

**Comment by boomberung** [comment]
Thank you a lot!
