### ISSUE TITLE
I can't find easy3d 

### ISSUE THREAD

**Issue by gleke** [LiangliangNan/Easy3D#132]
I can't  find easysd programe but Tutorial programe
/Easy3D/Release/bin$ ls
Tutorial_101_PointCloud                Tutorial_304_VectorField
Tutorial_102_PointCloud_Property       Tutorial_305_Texture
Tutorial_103_PointCloud_IO             Tutorial_306_Image
Tutorial_104_SurfaceMesh               Tutorial_307_Tessellator
Tutorial_105_SurfaceMesh_Connectivity  Tutorial_308_TexturedMesh
Tutorial_106_SurfaceMesh_Property      Tutorial_309_TextRendering
Tutorial_107_SurfaceMesh_IO            Tutorial_310_TextMesher
Tutorial_108_Graph                     Tutorial_311_Animation
Tutorial_109_Graph_Connectivity        Tutorial_312_MultiThread
Tutorial_110_Graph_Property            Tutorial_401_ModelPicker
Tutorial_111_Graph_IO                  Tutorial_402_FacePicker
Tutorial_112_PolyMesh                  Tutorial_403_PointSelection
Tutorial_113_PolyMesh_Connectivity     Tutorial_404_VirtualScanner
Tutorial_114_PolyMesh_Property         Tutorial_501_AmbientOcclusion
Tutorial_115_PolyMesh_IO               Tutorial_502_HardShadow
Tutorial_201_Viewer_imgui              Tutorial_503_SoftShadow
Tutorial_203_CompositeView             Tutorial_504_Transparency
Tutorial_204_CameraInterpolation       Tutorial_505_EyeDomeLighting
Tutorial_205_RealCamera                Tutorial_506_DepthMaps
Tutorial_301_Drawables                 Tutorial_601_Cloud_NormalEstimation
Tutorial_302_Imposters                 Tutorial_602_Cloud_SurfaceReconstruction
Tutorial_303_ScalarField               Tutorial_603_Cloud_PlaneExtraction

**Comment by gleke** [comment]
$ cd Easy3D
$ mkdir Release
$ cd Release
$ cmake -DCMAKE_BUILD_TYPE=Release ..
$ make

**Comment by LiangliangNan** [comment]
easy3d is a library that provides functions/classes for building 3D processing programs. There is no executable named "easy3d". 
I guess you mean Mapple? Check the [Build Easy3D](https://github.com/LiangliangNan/Easy3D#build-easy3d) section in the ReadMe file
