### ISSUE TITLE
How to display a mesh

### ISSUE THREAD

**Issue by esuig** [LiangliangNan/Easy3D#134]
Hello, 

how can I display a mesh (easy3d::SurfaceMesh) built with easy3d::SurfaceMeshBuilder? could you please point me to an example?

Thank you very much!

**Comment by LiangliangNan** [comment]
Below is the minimum code to visualize a mesh:

```C++
   // Initialize logging.
    logging::initialize();

    // Create the default Easy3D viewer.
    Viewer viewer("MyApp");

    // now add the mesh to your viewer.
    viewer.add_model(...).  // the argument can be either the path to the file or a pointer to a SurfaceMesh

    // Run the viewer
    return viewer.run();
```

There are many advanced examples showing how to visualize a mesh (or other models), see Tutorial_303, 304 ...

**Comment by esuig** [comment]
Thank you for your answer, I succeeded in displaying the mesh
