### ISSUE TITLE
orthogonal slices

### ISSUE THREAD

**Issue by kaigaox** [LiangliangNan/Easy3D#139]
I wonder if the library can render slices from a structured regular-spacing 3D volume, like this:
![coral](https://user-images.githubusercontent.com/10822134/194217059-831e4421-e138-47fd-9c41-e7ee13525845.png)
or this:
![salt](https://user-images.githubusercontent.com/10822134/194217140-419e10b6-6725-4a1d-aedc-9264ea0598be.png)
Thank you!

**Comment by kaigaox** [comment]
Could you please include an example code if possible? Thank you so much!

**Comment by LiangliangNan** [comment]
The current implementation doesn't support this.
It is doable by writing some shader code, but I currently don't have time for this. 
For general input (i.e., any 3D input), it can have a maximum number of 4 planes. But if this visualization is for a particular type of data, the maximum number can be larger. But that depends on what you actually want to visualize.

**Comment by kaigaox** [comment]
> Which software was used for producing the snapshots?
> 
> The current implementation doesn't support this. It is doable by writing some shader code, but I currently don't have time for this. For general input (i.e., any 3D input), it can have a maximum number of 8 planes (hardware dependent). But if this visualization is for a particular type of data, the maximum number can be larger. But that depends on what you actually want to visualize.

Got it. I produced these figures using VTK. The data are regularly spaced 3D arrays, i.e., arrays of size (n1, n2, n3) with regular spacing (d1, d2, d3). VTK has some functionalities to do this, but making Qt and VTK (both latest versions) work together can become a headache for me sometimes. Anyway, thank you for the answer!
