### ISSUE TITLE
Problem with make

### ISSUE THREAD

**Issue by boomberung** [LiangliangNan/Easy3D#14]
Hello!
Im using Ubutnu 18.04 and terminal versions of cmake and make.
Im clone your repo and
mkdir build && cd ./build
sudo cmake ..
cd ../
sudo make
then get this error

In file included from /home/garaev/Projects/Easy3D/easy3d/viewer/viewer.cpp:62:0:
/home/garaev/Projects/Easy3D/easy3d/util/timer.h: In lambda function:
/home/garaev/Projects/Easy3D/easy3d/util/timer.h:206:31: error: ‘bind’ is not a member of ‘std’
                 auto f = std::bind(func, owner, std::forward<Args>(args)...);
                               ^~~~
/home/garaev/Projects/Easy3D/easy3d/util/timer.h:206:31: note: suggested alternative: ‘find’
                 auto f = std::bind(func, owner, std::forward<Args>(args)...);
                               ^~~~
                               find
/home/garaev/Projects/Easy3D/easy3d/util/timer.h: In lambda function:
/home/garaev/Projects/Easy3D/easy3d/util/timer.h:238:27: error: ‘bind’ is not a member of ‘std’
             auto f = std::bind(func, owner, std::forward<Args>(args)...);
                           ^~~~
/home/garaev/Projects/Easy3D/easy3d/util/timer.h:238:27: note: suggested alternative: ‘find’
             auto f = std::bind(func, owner, std::forward<Args>(args)...);
                           ^~~~
                           find
/home/garaev/Projects/Easy3D/easy3d/util/timer.h: In lambda function:
/home/garaev/Projects/Easy3D/easy3d/util/timer.h:273:31: error: ‘bind’ is not a member of ‘std’
                 auto f = std::bind(func, owner, std::forward<Args>(args)...);
                               ^~~~
/home/garaev/Projects/Easy3D/easy3d/util/timer.h:273:31: note: suggested alternative: ‘find’
                 auto f = std::bind(func, owner, std::forward<Args>(args)...);
                               ^~~~
                               find
easy3d/viewer/CMakeFiles/viewer.dir/build.make:686: recipe for target 'easy3d/viewer/CMakeFiles/viewer.dir/viewer.cpp.o' failed
make[2]: *** [easy3d/viewer/CMakeFiles/viewer.dir/viewer.cpp.o] Error 1
CMakeFiles/Makefile2:609: recipe for target 'easy3d/viewer/CMakeFiles/viewer.dir/all' failed
make[1]: *** [easy3d/viewer/CMakeFiles/viewer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

How can i solve it?

**Comment by boomberung** [comment]
I find this is cuz bind become a member of std only in C++11 but where can i set the version of compiler?

**Comment by LiangliangNan** [comment]
For CMake ≥3.1, add 
 `set (CMAKE_CXX_STANDARD 11)`
before you define your target.
I don't have Linux and cannot test. Please let me know if it works.

**Comment by boomberung** [comment]
CMakeLists.txt on top level already have this line:
>set (CMAKE_CXX_STANDARD 11)
I add this line in file Easy3d/easy3d/utils/CMakeLists.txt, but nothing change.

**Comment by LiangliangNan** [comment]
Maybe you can do the following (a temporary solution, before I get a Linux to test):
The "Timer" is used only in viewer.cpp, comment out that code and remove the timer.h from easy3d.

I will post here when I figured out the problem.

**Comment by LiangliangNan** [comment]
![gcc](https://user-images.githubusercontent.com/15526536/57842038-060c1680-77cc-11e9-83c1-d7d3e1e026c9.png)
I tested under Ubuntu using the following available compilers (I added few missing header files. Please update your code first), all worked.
You can try including the header `#include <functional>` in timer.h. If your compiler could not find it, then your compiler doesn't support C++ 11 and you have to update your compiler.

**Comment by boomberung** [comment]
Thanks a lot, after adding in timer.h line:
>#include <functional>

all works for gcc compiler.
