### ISSUE TITLE
Scene centered by default

### ISSUE THREAD

**Issue by jeromeAlgoFace** [LiangliangNan/Easy3D#142]
Using the on Mac using rendering: the scene is centered by default. Is there a way to use library so that the scene is not centered?

**Comment by LiangliangNan** [comment]
I don't know which program you meant. 
If you use easy3d viewer, you can call  `return viewer.run(false);` (at the end of your main function).
The default argument value is `true` (i.e., `int Viewer::run(bool see_all = true)`), meaning all objects will be centered.

**Comment by jeromeAlgoFace** [comment]
I am using in composite viewer drawable->draw(cam); and cam->set_from_calibration(...)but it seems this is centering

**Comment by LiangliangNan** [comment]
It is not clear to me your workflow. Do you call `viewer.run()` after setting the camera from calibration? 
If so, call `viewer.run(false)`.
If not, do you call `viewer.fit_screen(...)`?you may need to look at [`void Viewer::fit_screen(const easy3d::Model *model)`](https://github.com/LiangliangNan/Easy3D/blob/d04ca9d13d2571ff4427d4eff5145bb8760f7d5a/easy3d/viewer/viewer.cpp#L1345) to get a clue.

**Comment by jeromeAlgoFace** [comment]
Thank you for your reply. 
I am working to change this system I was not using the library in the usual way..

**Comment by LiangliangNan** [comment]
I believe this issue has been resolved so I am going to close it.
Please feel free to reopen it if this is not the case.
