### ISSUE TITLE
The downloaded project is incomplete

### ISSUE THREAD

**Issue by fcyx** [LiangliangNan/Easy3D#146]
Hello, I found that gitclone cannot completely download projects, such as easy3d/util. After downloading, there are no initialize.cpp files

**Comment by LiangliangNan** [comment]
That is quite weird!!! As you can see the file is indeed here: https://github.com/LiangliangNan/Easy3D/blob/main/easy3d/util/initializer.cpp

Can you check if the file exists if you download from this releases?https://github.com/LiangliangNan/Easy3D/releases/tag/v2.5.2

**Comment by LiangliangNan** [comment]
That might be due to some Git issues. I will close this issue.

**Comment by fcyx** [comment]
Thank you for your reply！

The file download from this releases?https://github.com/LiangliangNan/Easy3D/releases/tag/v2.5.2 is complete and include the all code. 

And today I open the vpn to download through gitclone is complete, which should be my problem, thank you.
