### ISSUE TITLE
Problem with texture for .obj file

### ISSUE THREAD

**Issue by boomberung** [LiangliangNan/Easy3D#15]
I run viewer, press ctrl+O and load .obj file, but i see only mesh without texture. How can load .obj file with texture? For comparision in Meshlab this file opens with texture.
![Screenshot from 2019-05-19 15-27-55](https://user-images.githubusercontent.com/32163192/57982197-b8511180-7a4a-11e9-8590-1a45ca3b05ff.png)

**Comment by boomberung** [comment]
This file:

**Comment by boomberung** [comment]
Also in your example, the house has a texture, but when I run ./Tutorial_402_AmbientOcclusion I get a house without a texture.
![Screenshot from 2019-05-19 15-44-43](https://user-images.githubusercontent.com/32163192/57982371-56de7200-7a4d-11e9-822d-1db9ff549151.png)

**Comment by LiangliangNan** [comment]
The example uses a per-vertex color attribute (instead of texture).
I will add textured rendering to Easy3D and it may be available around the
summer (now too busy teaching). Please keep this issue open so you will
receive a notification when it is ready.

Best,
--
Liangliang

**Comment by LiangliangNan** [comment]
Hi, 
Just a quick update: now textured rendering is available in Easy3D. Check out the following two examples:
- `Tutorial_405_Texture`: rendering of a single textured quad;
- `Tutorial_407_TextureDMesh`: load and render a textured mesh (from an obj file).

**Comment by cmcneil** [comment]
Hello, this does not seem to work for me. I load an object (sitting next to a .mtl file and folder of textures) using Tutorial 407 (unmodified), and I get an untextured mesh. What kind of information might you like to investigate this issue? Thanks!!

**Comment by LiangliangNan** [comment]
That example shows how to *load* obj files and *upload texture* to the GPU.
Reading model files is implemented in “load_obj.cpp”, which is currently
not part of the default viewer.
When you load another model, it still calls to the “open()” function of the
viewer, in which only geometry is handled.
To load another model, you will need to override the behavior of the open()
function in the default viewer, i.e., to use the load_obj().

**Comment by LiangliangNan** [comment]
@cmcneil Hi, I managed to improve `Tutorial_407_TexturedMesh`, which is now able to load textured meshes in OBJ format. 
As you know, OBJ format can be extremely complex and it can only handle simple textured meshes. Smooth shading, free-form curve/surface, and physically-based Rendering parameters are not handled.
