### ISSUE TITLE
How can I translate a model?

### ISSUE THREAD

**Issue by KenKenhehe** [LiangliangNan/Easy3D#154]
How can I change the position of a loaded model (Surfacemesh, pointcloud), for example, mesh.x += ...,  mesh.y += ...,  mesh.z += ...

**Comment by LiangliangNan** [comment]
That is correct. For any type of model, you can transform it similarly. Below is an example:
```c++
    template<typename MODEL>
    void translate(MODEL* model, const vec3& p) {
        auto points = model->template get_vertex_property<vec3>("v:point");
        for (auto v : model->vertices())
            points[v] -= p;
    }
```

**Comment by KenKenhehe** [comment]
Thanks for getting back, what about rotation?

**Comment by LiangliangNan** [comment]
It is similar, e.g., 
```c++
    template<typename MODEL>
    void translate(MODEL* model, const mat4& R) {   // R is the rotation matrix
        auto points = model->template get_vertex_property<vec3>("v:point");
        for (auto v : model->vertices())
            points[v] = R * points[v];                                  // apply R to every vertex
    }
```

If you are visualizing the model using the Easy3D viewer, don't forget to call the following functions to update the viewer:
```c++
    model->renderer()->update();
    viewer->update();
```

**Comment by KenKenhehe** [comment]
Hi, thanks for the answers. 

Is there a easy way to convert euler angles(x, y, z) to a rotation matrix?

**Comment by LiangliangNan** [comment]
See here:
https://github.com/LiangliangNan/Easy3D/blob/1d1460cd179dbbb2293aa6c5828859697f08f36f/easy3d/core/mat.h#L2043
