### ISSUE TITLE
WritePNG

### ISSUE THREAD

**Issue by wangzhihao1226** [LiangliangNan/Easy3D#157]
hello,
I use the screenshot function and the saved PNG image has a very low resolution. Therefore, I want to save an image that is higher than the resolution of my screen display, how can I achieve that?

**Comment by wangzhihao1226** [comment]
Thank you very much for your quick reply. 
Sorry, maybe the description of my previous question was not comprehensive. I'll describe it again now: When I use the snapshot function, the generated image is still blurred even when I enlarge the model to the maximum, so I'd like to ask how to generate a higher resolution image. By the method you just used, the resolution of the image can be increased, but the clarity of the image is not improved.

**Comment by LiangliangNan** [comment]
What do you mean by "clarity" of image?
Can you show post your images here (Please show two images: one with the default resolution and the other one with the increased resolution)?

**Comment by wangzhihao1226** [comment]
![easy3d](https://user-images.githubusercontent.com/57579283/228115243-c08e8d1c-20eb-4f06-ab07-4cdcad4a8312.png)
![easy3d1](https://user-images.githubusercontent.com/57579283/228115250-267a2fab-8e8a-4978-a95f-0a4d3c7ba4c1.png)
Here I give the experimental results of Tutorial_201_Viewer_imgui,  where easy3d is the result of the original program implementation and easy3d1 is the result of the implementation by the method you mentioned before. Here is the code I modified according to your previous method:
`
bool Viewer::snapshot(const std::string& file_name, bool bk_white) const {
        int w, h;
        glfwGetFramebufferSize(window_, &w, &h);
        //////////////////////////////////////////
        double factor = 2.0;
        w = ceil(w * factor);
        h = ceil(h * factor);
        //////////////////////////////////////////
        FramebufferObject fbo(w, h, samples_);
        fbo.add_color_buffer();
        fbo.add_depth_buffer();
`
Although the resolution of the result is increased (800*600->1600*1200), the display content is not correspondingly larger and the final image quality&clear is not improved.

**Comment by LiangliangNan** [comment]
Indeed, the viewer size was not changed accordingly.

Now I have enhanced the snapshot function and made the scaling factor an argument. The updated code is in the *dev* branch (NOT the main branch). You can specify it in the following line (changing 1.0f to 2.0f or any other number greater than 1.0f). 
https://github.com/LiangliangNan/Easy3D/blob/c0d33778dfda22322ac1320a7bbbe6ea1a6e4241/easy3d/viewer/viewer.cpp#L1464
Please let me know if it works (and if so, I will push the changes to the main branch).

**Comment by LiangliangNan** [comment]
I would leave it to the users of Easy3D. In practice, people may want to increase the resolution after a preliminary one. So ideally it is expected to have a popup dialog asking the user to provide the relevant parameters.

I will close this issue now.

**Comment by wangzhihao1226** [comment]
Indeed, thank you very much for your help!
