### ISSUE TITLE
Can we highlight multiple faces? (Not entire model)

### ISSUE THREAD

**Issue by KenKenhehe** [LiangliangNan/Easy3D#162]
I am trying to highlight multiple faces for debugging purposes, but it seems like we can only highlight 1 face at a time(highlighting a new face automatically cancel the highlighting the old face)?

I am using this code to do the highlighting:
![image](https://github.com/LiangliangNan/Easy3D/assets/40273217/6db2acff-ca6f-4682-999d-1d888580671e)
"f" is a SurfaceMesh::Face structure

I find this this code here which seems to be the cause: 

![image](https://github.com/LiangliangNan/Easy3D/assets/40273217/8be523ff-4453-42ec-a31b-b75898527f27)

Is there any code we can use to prevent this behaviour? or do we need to implement this our self?

**Comment by KenKenhehe** [comment]
For 2), how does it render color attribute? Is there a code example?

**Comment by LiangliangNan** [comment]
First, add a color attribute to the faces:   
```c++          
     // add a color property called "f:color"
     auto face_color = mesh->add_face_property<vec3>("f:color", default_color);  
     // use the color property for rendering
     faces_drawable->set_property_coloring(State::FACE, "f:color");   
```
Then change the color of your interested faces by 
```c++          
     face_color[f] = vec3(1, 0, 0); 
```
Every time when the color/selection has changed, update the new color to GPU and informs the viewer:
```c++    
    mesh->renderer()->update();
    viewer_->update();
```

**Comment by KenKenhehe** [comment]
Thank you, this is helpful. I can implement this now, but would be good if you can also provide code example for 1)

**Comment by LiangliangNan** [comment]
> Thank you, this is helpful. I can implement this now, but would be good if you can also provide code example for 1)
The first option requires to sort the indices stored in the element array buffer in a way such that all your highlighted faces are stored consecutively. Below is an example:

Assume your indices are 
```c++
std::vector<GLuint> indices
{
    0, 1, 3,
    0, 3, 2,  <---- a face you want to highlight
    5, 7, 3,
    0, 5, 1,  <---- another face you want to highlight
    1, 2, 4,
    2, 0, 6   <---- the third face you want to highlight
};
```
You can sort the indices as
```c++
std::vector<GLuint> indices
{
    0, 1, 3,
    0, 3, 2,  <---- a face you want to highlight  ---- index in the range is 1
    0, 5, 1,  <---- another face you want to highlight
    2, 0, 6   <---- the third face you want to highlight  ---- index in the range is 3
    5, 7, 3,
    1, 2, 4
};
```
And then indicate the range of face indices (all faces with an index within this range will be highlighted):
```c+
drawable->set_highlight_range({1, 3});
```
