### ISSUE TITLE
How to draw a curve?

### ISSUE THREAD

**Issue by Roy2xc** [LiangliangNan/Easy3D#163]
I just copy the code of the example, but have trouble...

here is the screen shot:

![2 (2)](https://github.com/LiangliangNan/Easy3D/assets/42893773/c57a2532-3431-4ff8-ac66-3d425366a9d9)

I have included the header curve.h in my viewer.h.  and i'm using namespace of easy3d.

**Comment by LiangliangNan** [comment]
put "points" before "steps"

**Comment by LiangliangNan** [comment]
You should really read the document carefully ;-)
