### ISSUE TITLE
Off topic, compatibility questions: Will this work with unusual IDEs using old software versions?

### ISSUE THREAD

**Issue by XanCraft21** [LiangliangNan/Easy3D#167]
Hello, i would’ve opened this in discussion if the tab was available. I apologize for this being an invalid issue, i just had some questions to see if this library will meet my preferences and requirements.

I wanted to ask if this repo will work on development IDEs that use older versions of c++, specifically c++11, and that offloads the program to an external device, like using the Arduino IDE software on higher end processors.

I have gotten 2 3D renderer libraries to work in Arduino will little to no modification to the library code.

The first one is Small3DLib by DrummyFish on Codeberg. It runs pretty well but has texture perspective accuracy problems when stretching a small texture on a large model, and i need to create my own graphics functionality which means making a lighting engine from scratch which is pretty hard to do.

The second library is TinyGL by cChads here on github. It’s like a port of OpenGL and i had to make a small modification to make it work in Arduino. The library runs much faster than Small3DLib but texture perspective correct doesn’t work at all.

What i need is to see if this Library will work in Arduino or any IDE that used c++11, which is a bit outdated but it’s what I’m currently using at this time.

Can i extract the render buffer from a pointer and use it in my display library of choice, and how efficient is the perspective correction? Does your library have a decent lightweight lighting engine that uses point lights and other position based lighting, and how fast does all the rendering run?

Thank you for answering my questions and helping me confirm software compatibility. Again, sorry for making an invalid issue. Looking forward to your reply.

**Comment by LiangliangNan** [comment]
Easy3D used c++11 and the viewer is purely based on OpenGL. 
I have no experience with Arduino, so the easiest way to figure out if it meets your needs is to give it a try.
Of course, there is a lot that can be optimized for a specific hardware.

**Comment by XanCraft21** [comment]
Ok, thank you. I will try it and see what happens.

**Comment by XanCraft21** [comment]
Unfortunately this will not work for Arduino. I believe it is caused by computer hackers as i get them every day. I can close this issue now.
