### ISSUE TITLE
How to use Easy3D library in qt existing application

### ISSUE THREAD

**Issue by elenaVal** [LiangliangNan/Easy3D#17]
Hello,

At first thanks a lot for the library.
I really need what this library supports in my qt application. In particular, i would like to call the methods of this lib inside my qt application. However, i did not understand how i could this.

I would like to point out that i use cmake outside qt to configure the source code.
Could you please help me?
Thank you in advance,
Elena.

**Comment by LiangliangNan** [comment]
Please have a  look at the Qt Viewer example:
https://github.com/LiangliangNan/Easy3D/tree/master/tutorials/Tutorial_303_Viewer_Qt

The rendering is implemented using standard C++ and OpenGL, so you can copy the code from other examples.

**Comment by elenaVal** [comment]
Thanks a lot for you feedback. I tried to run this tutorial but i got back the following error:

> D:\Easy3D-master\Easy3D-master\tutorials\Tutorial_303_Viewer_Qt\viewer_qt.h:6: error: 
> easy3d/core/types.h: No such file or directory

Do you have any idea why i am getting back this error?
thanks in advance,
Elena.

**Comment by LiangliangNan** [comment]
In your CMakeList file, add the following line after `add_executable()`
`target_include_directories(${PROJECT_NAME} PRIVATE ${EASY3D_INCLUDE_DIR})`
This is to specify the path to the easy3d library (for the compiler to find the header files).

Please have a look at that CMakeList file in Tutorial_303_Viewer_Qt.

**Comment by elenaVal** [comment]
Hello again,

I finally manage to run the Tutorial_303_Viewer_Qt. However, when i am trying to open a model (i am trying to open a model from easy3D lib data folder. I got the following errors:

> OpenGL version requested: 4.3
Supported OpenGL version: 4.3.0 - Build 23.20.16.4973
Supported GLSL version:   4.30 - Build 23.20.16.4973
ViewerQt usage:                                                    
  F1:              Help											
  Ctrl + O:        Open file										
  Ctrl + S:        Save file										
  Left:            Orbit-rotate the camera							
  Right:           Move up/down/left/right							
  Alt + Left:      Orbit-rotate the camera (screen based)			
  Alt + Right:     Move up/down/left/right (screen based)			
  Middle/Wheel:    Zoom out/in										
  Ctrl + '-'/'+':  Zoom out/in										
  F:               Fit screen (all models)                         
  C:               Fit screen (current model only)					
  Shift + Right:   Set/unset anchor point							
  P:               Toggle perspective/orthographic projection)		
  A:               Toggle axes										
  W:               Toggle wireframe								
  < or >:          Switch between models							

>  Samples: 4 (4 requested, max support is 16)
> 
> vertex properties on mesh cube
> 	v:connectivity
> 	v:point
> 	v:deleted
> face properties on mesh cube
> 	f:connectivity
> 	f:deleted
> edge properties on mesh cube
> 	e:deleted
> load model done. time: 0.2ms
> mesh loaded. num faces: 6; num vertices: 8; num edges: 12
> GL error: 
> 	file: vertex_array_object.cpp
> 	line: 80
> 	function: bind
> 	info: Invalid operation (The specified operation is not allowed in the current state)
> GL error: 
> 	file: drawable.cpp
> 	line: 278
> 	function: draw
> 	info: Invalid operation (The specified operation is not allowed in the current state)

Could you please help me to figure what is going on?
Thanks a lot.

**Comment by LiangliangNan** [comment]
That's weird.  The viewer has been tested on Windows, Ubuntu, and Mac with 3 different graphics cards. 
It is possible to share with me your data so I can check?

**Comment by elenaVal** [comment]
For sure, how you want to share some of the models i am trying? 
Thank you in advance

**Comment by LiangliangNan** [comment]
Maybe a link to the data in DropBox, or you can use WeTransfer.

**Comment by elenaVal** [comment]
Thanks a lot for your quick response. Here you can find some of the .ply files that i am trying to open. 
[](https://www.dropbox.com/s/nzdyy71ivrl2djh/Ply.rar?dl=0)

**Comment by LiangliangNan** [comment]
Did you see warnings like
`vertex shader file 'lines_color.vert' does not exist
  vertex shader file 'points_color.vert' does not exist` ?

**Comment by elenaVal** [comment]
When i am trying to run the tutorial in the debug mode, i am getting as warnings the followings:

`GL error: 
	file: vertex_array_object.cpp
	line: 80
	function: bind
	info: Invalid operation (The specified operation is not allowed in the current state)`
etc.

Do you know what is the problem?

**Comment by LiangliangNan** [comment]
Could you please send me the information about your graphics card and the driver version?

**Comment by elenaVal** [comment]
Here you can find all  the info related to my graphic cards. 
https://www.dropbox.com/sh/sscjvq3kts95iiz/AAAMKKiZX1hEanO-oAZHcE1Za?dl=0

**Comment by elenaVal** [comment]
Here you can find all  the info related to my graphic cards. 
https://www.dropbox.com/sh/sscjvq3kts95iiz/AAAMKKiZX1hEanO-oAZHcE1Za?dl=0

**Comment by LiangliangNan** [comment]
Hi. The information is not sufficient to figure out the issue. I guess it is related to your hardware or graphics card driver. Could you please check which graphics card and the driver version your program is using (you have two graphics cards)? You can simply run the Viewer_Qt example and copy-paste the GPU info from the output. It is something like
> glDebugMessageCallback not available (requires OpenGL >= 4.3)
> OpenGL version requested: 4.3
> Supported OpenGL version: 4.1 ATI-2.8.38
> Supported GLSL version:   4.10

**Comment by LiangliangNan** [comment]
Hi @elenaVal, I reproduced the issues and it has been solved. The issue was that in Qt QOpenGLWidget draws everything into a framebuffer (for better performance) and I forgot to make the OpenGL context current before calling to the OpenGL functions to create the drawables.
Please update the code and let me know if it works or not.

**Comment by elenaVal** [comment]
Thanks a lot for you efforts. I will download the latest version of the source and i will let you know.

**Comment by elenaVal** [comment]
I just get the latest version, after Cmake runs successfully, i am trying to run some of the tutorial however, i got back the following error:

`D:\Easy3D-master\easy3d\util\timer.h:206: error: 'bind' is not a member of 'std'
                 auto f = std::bind(func, owner, std::forward<Args>(args)...);`

Do you know what causes this error?
Thanks a lot
                              `

**Comment by LiangliangNan** [comment]
now it should work (just added #include <functional> in timter.h).
Your compiler seems quite picky than my MS and Apple compilers.

**Comment by elenaVal** [comment]
Maybe the problem is with the compilers that i am using. I just tried to use the latest version of the code. If i use a compiler MinGW x86 (32 bit) i got back the following error.

`D:\Easy3D-master\3rd_party\glfw\src\win32_platform.h:69: error: dinput.h: No such file or directory
 #include <dinput.h>`

I have tried also to compile and run the code with MinGW 7.3.0 64bit, but i got back plenty of errors. Some of them are listed below (in total i got back 544 errors):

`C:\Users\elenv\AppData\Local\Temp\QtCreator-edtzCN\qtc-cmake-pJHZMPbQ\tutorials\Tutorial_303_Viewer_Qt\Tutorial_303_Viewer_Qt_autogen\mocs_compilation.cpp:-1: error: undefined reference to `__imp__ZNK11QObjectData17dynamicMetaObjectEv'`

`C:\Users\elenv\AppData\Local\Temp\QtCreator-edtzCN\qtc-cmake-pJHZMPbQ\tutorials\Tutorial_303_Viewer_Qt\Tutorial_303_Viewer_Qt_autogen\mocs_compilation.cpp:-1: error: undefined reference to `__imp__ZN11QMetaObject8activateEP7QObjectPKS_iPPv'`

`C:\Users\elenv\AppData\Local\Temp\QtCreator-edtzCN\qtc-cmake-pJHZMPbQ\tutorials\Tutorial_303_Viewer_Qt\Tutorial_303_Viewer_Qt_autogen\mocs_compilation.cpp:-1: error: undefined reference to `__imp__ZN11QMainWindow11qt_metacallEN11QMetaObject4CallEiPPv'`

`C:\Users\elenv\AppData\Local\Temp\QtCreator-edtzCN\qtc-cmake-pJHZMPbQ\tutorials\Tutorial_303_Viewer_Qt\Tutorial_303_Viewer_Qt_autogen\mocs_compilation.cpp:-1: error: undefined reference to `QMainWindow::event(QEvent*)'
`
Thanks a lot

**Comment by LiangliangNan** [comment]
I just tried and MinGW 64bit worked perfectly.
Please make sure the Qt you use is also compiled using the same compiler,
i.e., MinGW 64bit  (you may have multiple version of Qt binaries).
Please clean or delete the entire build dir to start a new build.
--
Liangliang

**Comment by elenaVal** [comment]
Thank you so much, i change the compiler now everything is working fine! I could load point cloud as well as mesh models. 

One more question that i have is about the colors. I realized that the viewer doesn't take under consideration the colors of the ply file. Is it possible to include this color-info as well?

**Comment by LiangliangNan** [comment]
Yes. That is definitely doable. You need to call the following two functions after you create the drawable:
> 	drawable->update_color_buffer(colors);   // transfer the color data to the GPU.	
> 	drawable->set_per_vertex_color(true);      // vertices have varying colors. 
Please have a look at `Easy3D/tutorials/Tutorial_402_ScalarField/main.cpp` for example.

**Comment by elenaVal** [comment]
I run some tests and it seems that with some models everything is running fine as well as giving the correct color/vertex. However, with some models the color of all the vertices are black. 

I make a test, just disable (set false the following command)
`drawable->set_per_vertex_color(false);`

And then the black vertices are colored with "default" color, so it seems that the commands are working but the colors are not "transfer" correctly?

**Comment by LiangliangNan** [comment]
You have to make sure the number of RGB coordinates == the number of XYZ
coordinates, and drawable->set_per_vertex_color(*true*);
--
Liangliang

**Comment by elenaVal** [comment]
Ι got the point. Thanks a lot for your support!
