### ISSUE TITLE
Problem with V2.5.2: failed to make context current

### ISSUE THREAD

**Issue by yvanblanchard** [LiangliangNan/Easy3D#170]
Hello,

I downloasded the v2.5.2 binaries, for Windows, and when launching Mapple.Exe, I have an empty window with folllowing messages in console:

![image](https://github.com/LiangliangNan/Easy3D/assets/63931618/77bcd9f3-c97c-43ea-82f2-b55ed106fa54)

What's wrong ?
Thank you.

**Comment by LiangliangNan** [comment]
See the explanation and setup here:
https://github.com/LiangliangNan/Easy3D/issues/158
________________________________
From: Yvan Blanchard ***@***.***>
Sent: Saturday, August 26, 2023 4:17:02 PM
To: LiangliangNan/Easy3D ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LiangliangNan/Easy3D] Problem with V2.5.2: failed to make context current (Issue #170)


Hello,

I downloasded the v2.5.2 binaries, for Windows, and I have an empty window with folllowing messages in console:

[image]<https://user-images.githubusercontent.com/63931618/263451410-77bcd9f3-c97c-43ea-82f2-b55ed106fa54.png>

What's wrong ?
Thank you.

**Comment by yvanblanchard** [comment]
Thank you @LiangliangNan 
Could you consider by automatically detect the most powerful Graphical card ? there are some simple APIs for doing that.

**Comment by LiangliangNan** [comment]
When using Vulkan, it can, but not possible with OpenGL.

Best,
--
Liangliang
________________________________
