### ISSUE TITLE
How do I add new button functions

### ISSUE THREAD

**Issue by Bobkk-k** [LiangliangNan/Easy3D#171]
I want to implement the point cloud to be colored by categories, this is I currently according to the tutorial to write, but always report errors, can you help me？
![image](https://github.com/LiangliangNan/Easy3D/assets/78141973/9b5f2a45-1d73-4613-8fb9-979fb46f930b)

**Comment by LiangliangNan** [comment]
`colors[v] = random_color()` is apparently not correct, because it assigns a random color for each vertex.
The correct way to do it is to first generate a ***unique*** color for ***each*** category. Then for each vertex you assign a color based on its category.

**Comment by Bobkk-k** [comment]
> What are the errors did you see? Better to post the error messages or snapshots here.
> 
> Besides, your code also has logical errors. `colors[v] = random_color()` is apparently not correct, because it assigns a random color for each vertex. The correct way to do it is to first generate a _**unique**_ color for _**each**_ category. Then for each vertex you assign the predefined color queried based on its category.

Thanks to your reply. I'm sorry I didn't express my problem clearly, I main problem is I don't know which function to use to make vertexs colorize by its color property. `set_coloring`function seems dosen't work. But I have find a function to do this, it is update_color_buffer().

now I met a new problem. The `update_color_buffer()` function dosen't work, after I use  `set_uniform_coloring` function. It seems once I use `set uniform_coloring` function, I can't colorize my vertexs by different colors.

**Comment by LiangliangNan** [comment]
Your previous question:
You can call `Drawable::update()` function after calling to `set_coloring(...)` to actually transfer the color information to GPU. You will also need to call your viewer's `update()` function to update the display.

Your second question: 
Of course, because you asked to use uniform color for all vertices (because of the call to `set_uniform_coloring()`).

**Comment by Bobkk-k** [comment]
I got it. Thank you so much！！
