### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by jigneshBadrakhiya** [LiangliangNan/Easy3D#172]
wire fame back-face culling

**Comment by LiangliangNan** [comment]
BFC works well only when handling closed convex objects, and in most real-world cases we are handling non-perfect models. Thus I don't think it is worth to enable it by default. But if you want, you can simply enable it by adding the following two lines when you initialize OpenGL:

```c++
       glEnable(GL_CULL_FACE);
       glCullFace(GL_BACK);
```
