### ISSUE TITLE
how to automate the RANSAC primitive extraction and how to use it in python project. 

### ISSUE THREAD

**Issue by vedantpatel41** [LiangliangNan/Easy3D#175]
Hello there!

I hope this message finds you well. I'm currently working on a 3D reconstruction project, and I'm in need of RANSAC primitive extraction from Mapple. I'm running reconstructions on multiple files and aiming to automate this process.

I'd greatly appreciate your guidance on how to integrate RANSAC primitive extraction into my project. If you have any insights or recommendations on how I can achieve automation, I would be grateful for your assistance.

**Comment by LiangliangNan** [comment]
The basic usage is
```c++
    auto cloud = dynamic_cast<PointCloud *>(model);
    auto normals = cloud->get_vertex_property<vec3>("v:normal");
    if (!normals) {
        std::cerr << "Plane extraction using RANSAC requires normal information but it is not available" << std::endl;
        return false;
    }

    PrimitivesRansac algo;
    algo.add_primitive_type(PrimitivesRansac::PLANE);  // Tell the algorithm to extract planes only (you can also add other types)

    // you can try different parameters of RANSAC (usually you don't need to tune them)
    const int num = algo.detect(cloud, 200, 0.005f, 0.02f, 0.8f, 0.001f);
    if (num > 0) {
        std::cout << num << " primitives extracted" << std::endl;
        ... Then the results are stored as per-point properties:
             - "v:primitive_type"  (one of PLANE, SPHERE, CYLINDER, CONE, TORUS, and UNKNOWN)
             - "v:primitive_index" (-1, 0, 1, 2...). -1 meaning a vertex does not belong to any primitive (thus its primitive_type must be UNKNOWN.
    }
````
![image](https://github.com/LiangliangNan/Easy3D/assets/15526536/a0dad903-6c42-49dd-8e63-ed3ccfa36010)

Please check the example at `tutorials/Tutorial_703_Cloud_PlaneExtraction` and also [point_cloud_ransac.h](https://github.com/LiangliangNan/Easy3D/blob/main/easy3d/algo/point_cloud_ransac.h) for more details.

**Comment by zeyadmahmoudd** [comment]
Dear Sir,
Hope all is well with you. I had a question, Can I Ransac Plane Extraction inside Mapple GUI?

**Comment by LiangliangNan** [comment]
Yes. Please check out the "Primitive extraction" menu under "Point cloud".

Best,
--
Liangliang
________________________________

**Comment by zeyadmahmoudd** [comment]
![Screenshot 2024-07-29 at 10 38 19 AM](https://github.com/user-attachments/assets/5430401a-ad48-4e11-baf2-f480756e1a85)
I can't find Primitive Extraction under points, or there is another menu called pointclouds not points?
Because I can't find it.
Thanks for your time and effort.
