### ISSUE TITLE
[HELP] - wrong compile about nanoflann package

### ISSUE THREAD

**Issue by sli1989** [LiangliangNan/Easy3D#182]
**Describe the bug**. 

**Tell us how to reproduce the bug**. 
Is it a compile time error or runtime issue?
 - For compile time issues, post here the code and full compile log.
 - For runtime issues, post here screenshots (of the results or error messages), as well as the complete run log of the program. You can change "initialize()" to "initialize(true)" in your "main()" function, and then a log file will be generated next to the executable after you run the program. If running the program involves multiple user inputs, then please also describe the steps so the issue can be reproduced.  
In all cases, post your code and data here (if relevant).

**Development/Running environment:**
 - OS: Windows 10
 - Compiler MSVC++ 14.0
 - lastest master branch

**Additional context**. 

when nmake with VS2015, there some thine wrong in 'nanoflann.hpp' and nanoflann-related files.

- C2146 - syntax error: missing ';' before identifier 'size_type' 
- C4430 - missing type specifier - int assumed.

There seems to be no problem with program semantics, and nothing to know to fix it unless comment the nanoflann-related in cmakelist.

thanks

**Comment by LiangliangNan** [comment]
can you post the entire compiler log here?

**Comment by sli1989** [comment]
Seems followed the intruction. The step for reproduction
1.  install vs_community__2015
2. install  cmake-3.29
3. using `x64 Native Tools Command Prompt`
4. `cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release64 .. `
5. `nmake`

but reproduced in vs_community__2017, the errors C2146 and C4430 is missing with some warning information, which can be executed successfully.

And, `#include <string>` seems needed add in head file of `\Easy3D\easy3d\util\console_style.cpp` to avoid `error C2679: binary '<<': no operator found`.

**Comment by LiangliangNan** [comment]
So the error is only with vs 2015 and it works well with vs 2017?
In my past test, it worked well with vs2019 and vs 2022 (but it has not been tested with vs2015 and vs2017).

Anyway, I have added  `#include <string>` to `console_style.cpp`.
