### ISSUE TITLE
Model Matrix

### ISSUE THREAD

**Issue by Champion-zzy** [LiangliangNan/Easy3D#183]
Hello, Professor Nan! I would like to inquire about a convenient method to obtain the model matrix of a surface mesh model.

**Comment by LiangliangNan** [comment]
I didn't quite understand your question. Do you mean when the mesh is being visualized in the viewer, how to query the model-view matrix with respect to the current view? 
If so, please check the following function in the `Camera` class.
https://github.com/LiangliangNan/Easy3D/blob/7e47b17175ae89380013329d1eb142e9b3909d8f/easy3d/renderer/camera.h#L448

**Comment by Champion-zzy** [comment]
I want to control the translation and rotation transformations of individual objects instead of the entire scene, and manipulating the camera cannot achieve this. Are there any good ways？

**Comment by LiangliangNan** [comment]
Easy3D has an object manipulator that is for manipulating models. Please check out[Tutorial_405_ObjectManipulation](https://github.com/LiangliangNan/Easy3D/tree/main/tutorials/Tutorial_405_ObjectManipulation).

**Comment by Champion-zzy** [comment]
Thank you very much for Professor Nan's answer.
