### ISSUE TITLE
[BUG] - maple.exe v2..5.4 does not open on windows

### ISSUE THREAD

**Issue by bgpantojar** [LiangliangNan/Easy3D#194]
**Describe the bug**. 
I just download the realeased version v2.5.4 of mapple and open it on windows and it does not open.

**Tell us how to reproduce the bug**. 
Opening maple.exe displays this error stored in the log file.

================================================================= program started ...
V 16/10/2024 19:38:22.809 logging.cpp:201] executable path: C:\Bryan\Programs\Mapple_for_Windows_v2.5.4\Mapple_v2.5.4
V 16/10/2024 19:38:22.809 logging.cpp:202] current working dir: C:\Bryan\Programs\Mapple_for_Windows_v2.5.4\Mapple_v2.5.4
I 16/10/2024 19:38:22.809 setting.cpp:285] setting file created: C:\Bryan\Programs\Mapple_for_Windows_v2.5.4\Mapple_v2.5.4\Mapple.ini
F 16/10/2024 19:38:23.514 logging.cpp:105] Application has crashed due to [SIGSEGV] signal
    Invalid access to memory
    Program is trying to read an invalid (unallocated, deleted or corrupted) or inaccessible memory.
=================================================================================
Easy3D has encountered a fatal error and has to abort. The error has been recorded 
in the log file [C:\Bryan\Programs\Mapple_for_Windows_v2.5.4\Mapple_v2.5.4\Mapple.log].
Please report this issue with the complete log, a description of how to reproduce
the issue, and possibly your data to Liangliang Nan (liangliang.nan@gmail.com).
=================================================================================
*** Check failure stack trace (most recent call first): ***

**Development/Running environment:**
OS Name	Microsoft Windows 11 Home
Installed Physical Memory (RAM)	32.0 GB
 NVIDIA GeForce RTX 3060 6GB
Processor 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, 2304 Mhz, 8 Core(s), 16 Logical Processor(s)
System Model	ASUS TUF Gaming F15 FX506HM_FX506HM

 - Compiler. binary file
 - Debug or release? v2.5.4

**Comment by LiangliangNan** [comment]
Have you checked the ReadMe.txt file, and tested Mapple after installing the Visual Studio redistributable package "vc_redist.x64.exe" (in the "backup" folder)?
Then if it still crashes, please post the whole log of Mapple here (in the Mapple.log file after running it).
