### ISSUE TITLE
[BUG] - Why  my computer can't run Mappple properly

### ISSUE THREAD

**Issue by DWR-CMQ** [LiangliangNan/Easy3D#195]
When I double click Mapple icon
![image](https://github.com/user-attachments/assets/c73201b5-2724-42cd-b747-1da0780721a7)
It flashes an interface, and the log displays 
![image](https://github.com/user-attachments/assets/86dbc5de-f817-4151-afeb-5bdea34c128b)
My computer is win10, has installed the 'vc_redist.x64.exe' (in the 'backup' directory).

**Comment by LiangliangNan** [comment]
What are the messages from the console window?

**Comment by LiangliangNan** [comment]
That is strange. I have a few stduents who have been using Mapple on Windows for quite a while and without any problem.
Based on the very limited input/observation, it is not possbile to figure out the issue.
Have you tried any of the previous releases, e.g., [v2.5.2](https://github.com/LiangliangNan/Easy3D/releases/tag/v2.5.2)?

On my machine, the log file looks like:

```
================================================================= program started ...
V 04/11/2024 22:51:57.169 logging.cpp:201] executable path: C:\Users\liang\Downloads\Mapple_v2.5.4
V 04/11/2024 22:51:57.169 logging.cpp:202] current working dir: C:\Users\liang\Downloads\Mapple_v2.5.4
I 04/11/2024 22:51:57.170 setting.cpp:285] setting file created: C:\Users\liang\Downloads\Mapple_v2.5.4\Mapple.ini
V 04/11/2024 22:51:57.721 resource.cpp:49] resource directory: F:\3_code\Easy3D\resources
I 04/11/2024 22:51:58.951 main.cpp:179] log file: C:\Users\liang\Downloads\Mapple_v2.5.4\Mapple.log
V 04/11/2024 22:51:59.009 paint_canvas.cpp:203] OpenGL vendor: NVIDIA Corporation
V 04/11/2024 22:51:59.009 paint_canvas.cpp:204] OpenGL renderer: NVIDIA GeForce RTX 3090/PCIe/SSE2
V 04/11/2024 22:51:59.009 paint_canvas.cpp:205] OpenGL version requested: 4.3
V 04/11/2024 22:51:59.009 paint_canvas.cpp:206] OpenGL version received: 4.3.0 NVIDIA 560.94
V 04/11/2024 22:51:59.009 paint_canvas.cpp:207] GLSL version received: 4.30 NVIDIA via Cg compiler
V 04/11/2024 22:51:59.009 paint_canvas.cpp:222] DPI scaling: 1
V 04/11/2024 22:51:59.014 text_renderer.cpp:756] loaded font 'en_Earth-Normal.ttf' in texture (512 x 512)
V 04/11/2024 22:51:59.016 text_renderer.cpp:756] loaded font 'en_Roboto-Medium.ttf' in texture (512 x 512)
V 04/11/2024 22:51:59.105 paint_canvas.cpp:1130] Samples received: 4 (4 requested, max support is 32)

```

**Comment by LiangliangNan** [comment]
@DWR-CMQ 
I've just rebuit Mapple. Can you try it again from here? 
https://github.com/LiangliangNan/Easy3D/releases/download/v2.5.4/Mapple_for_Windows_v2.5.4.zip

The previous one you tested was built with VS 2022, but the windows redistributables were shipped for VS2019. But I am not sure if this caused the problem on your Windows.

**Comment by DWR-CMQ** [comment]
still not working, I don't know why.But it's okay, I built the solution and can run the Mapple successfully
![image](https://github.com/user-attachments/assets/c951d820-1930-4136-8b40-8e25de9fbc8e)
Thanks!

**Comment by LiangliangNan** [comment]
I guess the failure might be due some of the 3rd party libraries (e.g., Qt, OpenGL, FFMPEG) are not compatible with your Windows distribution. 
But glad you built it from the source code. So I am closing this issue now.
