### ISSUE TITLE
Is there a function to edit vertices?

### ISSUE THREAD

**Issue by DWR-CMQ** [LiangliangNan/Easy3D#196]
Is there a function to edit vertices?for example, select partial verticels and delete

**Comment by LiangliangNan** [comment]
Yes. Mapple demonstrates these functionalities.

Besides, [Tutorial_403_PointSelection](https://github.com/LiangliangNan/Easy3D/tree/main/tutorials/Tutorial_403_PointSelection) demonstrates similiar functions for selecting points. Then in the PointCloud data structure there are corresponding functions for deletecting the vertices. 
The similar functions are also provided for SurfaceMesh.

**Comment by DWR-CMQ** [comment]
Yeah!I found it.Thanks
