### ISSUE TITLE
About meshSmoothing.

### ISSUE THREAD

**Issue by DWR-CMQ** [LiangliangNan/Easy3D#197]
Hi, I have several questions.
1:In surface_mesh_smoothingcpp,Why are there two kinds of mesh filtering, namely explicit and implicit?  
![image](https://github.com/user-attachments/assets/b54e0e8a-29de-4e93-8a4a-b92888cc8ba5)
![image](https://github.com/user-attachments/assets/fde05c45-f9a1-4b71-ac6c-3eef0d85e662)

2:In the implicit_smoothing function.Where does the mathematical principle of this code come from, or from which paper do, I want to know,especially the red box.
![image](https://github.com/user-attachments/assets/e6e7f65b-2260-40c2-9664-680986cc37f5)
![image](https://github.com/user-attachments/assets/62c9676b-5234-4510-b4dd-9e0e3b12a320)

**Comment by LiangliangNan** [comment]
See the following papers for more details:  

- Mathieu Desbrun et al. Implicit fairing of irregular meshes using diffusion and curvature flow. SIGGRAPH, 1999.

-  Misha Kazhdan et al. Can mean‐curvature flow be modified to be non‐singular? CGF, 2012.

**Comment by DWR-CMQ** [comment]
I took a look at the outline, but there's very little about boundary handling, in the code, when you hit a boundary, why do you deal with the right-hand side matrix B.I know I'm offensive, but I really want to know how it works.
![image](https://github.com/user-attachments/assets/c30fd462-8afd-4767-81d0-6a1ce7310877)

**Comment by LiangliangNan** [comment]
Because we want to keep the boundaries fixed.

**Comment by DWR-CMQ** [comment]
:hot_face:,I still do not understand the formula for boundary ,I find "mesh shrink in smoothing’ in google,but I still can't find a mathematical formula for it
![image](https://github.com/user-attachments/assets/141de3c9-51c6-4d84-aade-5593c0d929ed)
I believe that any computational logic is derived from mathematics (textbook or paper). Or is it an empirical formula?
And I found out that fairing, hole_filling,parameteriazation perform similar operations

**Comment by LiangliangNan** [comment]
It is not an empirical formula.
If you expand the linear system Ax = b, you will see that the equation for a boundary vertex v has exactly the form:
`weight * v = weight * v`. This is exact what we want to preserve the position of v.

Since this is ideed not an issue, so I am closing it now. Feel free to follow with further questions.
