### ISSUE TITLE
How to call Easy3D functions in python?

### ISSUE THREAD

**Issue by QweAsdZxcMnbLkjPoi** [LiangliangNan/Easy3D#198]
Hello!
Thank you for your wonderful 3D processing library and software!

###  Problem
I want to do some processing for point clouds including estimating normals and Poisson reconstruction, maybe with fairing after that. I have tried out the version with GUI on Windows and found the full process working well with satisfactory results.

Now, I'm trying to integrate the process into my python scripts. But unfortunately, I have no experience in C++ programming, and I don't know how to integrate libraries written in C++ to python code.

### Detailed information I want to know
I wonder how to load my data for Easy3D and how to call functions from Easy3D in python? 

**Or alternatively**, can I process the data in **linux console** using command lines? Because I can use console commands in python scripts.

So if there is an example for python or console will be great: (1) Read point cloud data for Easy3D. (2) Call function that estimates normal or other processing. (3) Save point cloud or mesh to a .ply file.

It will be really helpful if you can provide any information! Thank you in advance for your assistance!

**Comment by LiangliangNan** [comment]
Hi, I've just written an incomplete Python binding of easy3d (and it is only limited to file IO and normal estimation).
Here you can see the bindings, with a simple example written in Python:
https://github.com/LiangliangNan/Easy3D/tree/main/python

With this, you should be able to do file read/write, and normal estimation using Easy3D.
A full set of Python bindings may be available later (I cannot promise when it will be ready).
See also issue #63.

**Comment by QweAsdZxcMnbLkjPoi** [comment]
Thank you for the incomplete Python binding of easy3d!

These days I'm trying to add functions of Poisson reconstruction, surface io, and fairing by myself to your example.
This is the fileio_bindings.cpp after my changes:

```
#include <pybind11/pybind11.h>

#include <easy3d/core/point_cloud.h>
#include <easy3d/fileio/point_cloud_io.h>
#include <easy3d/core/surface_mesh.h>
#include <easy3d/fileio/surface_mesh_io.h>

namespace py = pybind11;

void bind_point_cloud_io(py::module_ &m) {
    py::class_<easy3d::PointCloudIO>(m, "PointCloudIO")
        .def_static("load",
                    &easy3d::PointCloudIO::load,
                    py::arg("file_name"),
                    "Reads a point cloud from file")
        .def_static("save",
                    &easy3d::PointCloudIO::save,
                    py::arg("file_name"),
                    py::arg("cloud"),
                    "Saves a point cloud to a file");

    py::module_ io = m.def_submodule("io", "IO operations for point clouds");

    io.def("load_bin",
           &easy3d::io::load_bin,
           py::arg("file_name"),
           py::arg("cloud"),
           "Reads point cloud from a bin format file");
    io.def("save_bin",
           &easy3d::io::save_bin,
           py::arg("file_name"),
           py::arg("cloud"),
           "Saves a point cloud to a bin format file");
    io.def("load_xyz",
           &easy3d::io::load_xyz,
           py::arg("file_name"),
           py::arg("cloud"),
           "Reads point cloud from an xyz format file");
    io.def("save_xyz",
           &easy3d::io::save_xyz,
           py::arg("file_name"),
           py::arg("cloud"),
           "Saves a point cloud to an xyz format file");
    io.def("load_bxyz",
           &easy3d::io::load_bxyz,
           py::arg("file_name"),
           py::arg("cloud"),
           "Reads point cloud from a binary xyz format file");
    io.def("save_bxyz",
           &easy3d::io::save_bxyz,
           py::arg("file_name"),
           py::arg("cloud"),
           "Saves a point cloud to a binary xyz format file");
///////////////////////////////////////////////////////////////////////
    io.def("load_ply",
           &easy3d::io::load_ply,
           py::arg("file_name"),
           py::arg("cloud"),
           "Reads point cloud from a ply format file");
    io.def("save_ply",
           &easy3d::io::save_ply,
           py::arg("file_name"),
           py::arg("cloud"),
           py::arg("binary") = true,
           "Saves a point cloud to a ply format file");
///////////////////////////////////////////////////////////////////////
    io.def("load_las",
           &easy3d::io::load_las,
           py::arg("file_name"),
           py::arg("cloud"),
           "Reads point cloud from a las/laz format file");
    io.def("save_las",
           &easy3d::io::save_las,
           py::arg("file_name"),
           py::arg("cloud"),
           "Saves a point cloud to a las/laz format file");
}

void bind_surface_mesh_io(py::module_ &m) {
    py::class_<easy3d::SurfaceMeshIO>(m, "SurfaceMeshIO")
        .def_static("load",
                    &easy3d::SurfaceMeshIO::load,
                    py::arg("file_name"),
                    "Reads a surface mesh from file")
        .def_static("save",
                    &easy3d::SurfaceMeshIO::save,
                    py::arg("file_name"),
                    py::arg("mesh"),
                    "Saves a surface mesh to a file");

    py::module_ io = m.def_submodule("io", "IO operations for surface meshes");

    io.def("load_sm",
           &easy3d::io::load_sm,
           py::arg("file_name"),
           py::arg("mesh"),
           "Reads surface mesh from an SM format file");
    io.def("save_sm",
           &easy3d::io::save_sm,
           py::arg("file_name"),
           py::arg("mesh"),
           "Saves a surface mesh to an SM format file");
///////////////////////////////////////////////////////////////////////   
    io.def("load_ply",
           &easy3d::io::load_ply,
           py::arg("file_name"),
           py::arg("mesh"),
           "Reads surface mesh from a PLY format file");
    io.def("save_ply",
           &easy3d::io::save_ply,
           py::arg("file_name"),
           py::arg("mesh"),
           py::arg("binary") = true,
           "Saves a surface mesh to a PLY format file");
///////////////////////////////////////////////////////////////////////
    io.def("load_off",
           &easy3d::io::load_off,
           py::arg("file_name"),
           py::arg("mesh"),
           "Reads surface mesh from an OFF format file");
    io.def("save_off",
           &easy3d::io::save_off,
           py::arg("file_name"),
           py::arg("mesh"),
           "Saves a surface mesh to an OFF format file");
    io.def("load_obj",
           &easy3d::io::load_obj,
           py::arg("file_name"),
           py::arg("mesh"),
           "Reads surface mesh from an OBJ format file");
    io.def("save_obj",
           &easy3d::io::save_obj,
           py::arg("file_name"),
           py::arg("mesh"),
           "Saves a surface mesh to an OBJ format file");
    io.def("load_stl",
           &easy3d::io::load_stl,
           py::arg("file_name"),
           py::arg("mesh"),
           "Reads surface mesh from an STL format file");
    io.def("save_stl",
           &easy3d::io::save_stl,
           py::arg("file_name"),
           py::arg("mesh"),
           "Saves a surface mesh to an STL format file");
    io.def("load_trilist",
           &easy3d::io::load_trilist,
           py::arg("file_name"),
           py::arg("mesh"),
           "Reads a set of triangles from a file");
    io.def("load_geojson",
           &easy3d::io::load_geojson,
           py::arg("file_name"),
           py::arg("mesh"),
           "Reads surface mesh from a Geojson format file");
}


PYBIND11_MODULE(easy3d_fileio, m) {
    m.doc() = "Bindings for Easy3D fileio functions";

    bind_point_cloud_io(m);
    bind_surface_mesh_io(m);
}
```

When I run `make`, it shows errors like this:

```
[ 50%] Building CXX object CMakeFiles/easy3d_fileio.dir/fileio_bindings.cpp.o
/root/project/roofdataset_code/Easy3D-main/python/fileio_bindings.cpp: In function ‘void bind_point_cloud_io(pybind11::module_&)’:
/root/project/roofdataset_code/Easy3D-main/python/fileio_bindings.cpp:58:54: error: no matching function for call to ‘pybind11::module_::def(const char [9], <unresolved overloaded function type>, pybind11::arg, pybind11::arg, const char [41])’
            "Reads point cloud from a ply format file");
                                                      ^
```

inside the code block where I use "///////////////////////////////////////////////////////////////////////" to emphasize.
I find under `easy3d/fileio/` folder, there are files like `ply_reader_writer.cpp`, `ply_reader_writer.h`. Maybe we should use them to update the code?

**Comment by QweAsdZxcMnbLkjPoi** [comment]
> It seems like we need to overload the functions with the same name, could you please help me here?

Maybe it is not overload, but we should have a `point_cloud_fileio_bindings.cpp` and a `surface_mesh_fileio_bindings.cpp`?

**Comment by QweAsdZxcMnbLkjPoi** [comment]
I have separate `fileio_bindings.cpp` into two files `point_cloud_fileio_bindings.cpp` and `surface_mesh_fileio_bindings.cpp` and changed some variable names, `make` runs successfully.

**Comment by LiangliangNan** [comment]
Glad to hear it works.
I will work on the Python bindings to make it (reasonably) complete. 
Hopefully it will be available soon :-)

**Comment by LiangliangNan** [comment]
> I have separate `fileio_bindings.cpp` into two files `point_cloud_fileio_bindings.cpp` and `surface_mesh_fileio_bindings.cpp` and changed some variable names, `make` runs successfully.

I agree that it makes sense to have a `xxx_bindings.cpp` for each corresponding `.h` file.
Especially when there is a large number of classes/functions to be exposed to Python.

**Comment by LiangliangNan** [comment]
Python bindings for Easy3D (the most useful parts) are now available here:
https://github.com/LiangliangNan/Easy3D/tree/main/python
For the build and installation of the Python bindings, check [here](https://github.com/LiangliangNan/Easy3D/blob/main/ReadMe.md#build-and-install-python-bindings).

Some available examples:
https://github.com/LiangliangNan/Easy3D/tree/main/python/examples
The remaining part will be continuously tested, and examples will be added.

**Comment by QweAsdZxcMnbLkjPoi** [comment]
> Python bindings for Easy3D (the most useful parts) are now available here: https://github.com/LiangliangNan/Easy3D/tree/main/python For the build and installation of the Python bindings, check [here](https://github.com/LiangliangNan/Easy3D/blob/main/ReadMe.md#build-and-install-python-bindings).
> 
> Some available examples: https://github.com/LiangliangNan/Easy3D/tree/main/python/examples The remaining part will be continuously tested, and examples will be added.

Thank you very much!
