### ISSUE TITLE
Why can't I find the DLL file

### ISSUE THREAD

**Issue by ac416** [LiangliangNan/Easy3D#199]
![image](https://github.com/user-attachments/assets/287923c0-bf07-4051-ac74-b9bc188a6ba4)

**Comment by LiangliangNan** [comment]
On Windows, you will need to add the "bin" dir (e.g.,  "F:/tools/Easy3D main/Release/bin" to your "PATH" environmental variable.
This way, your program that depends on Easy3D will know where to find the Easy3D DLLs.

**Comment by LiangliangNan** [comment]
This is not an issue. So I am closing it now.

**Comment by ac416** [comment]
Thank you, it's okay now

> On Windows, you will need to add the "bin" dir (e.g., "F:/tools/Easy3D main/Release/bin" to your "PATH" environmental variable. This way, your program that depends on Easy3D will know where to find the Easy3D DLLs.
