### ISSUE TITLE
Running viewer->run() inside a thread crashes 

### ISSUE THREAD

**Issue by alior101** [LiangliangNan/Easy3D#26]
Hi,
When I run the viewer->run() inside a thread (in order no to block my main program execution) imgui crash 

`Visualizer::Visualizer()
{
   	viewer = new easy3d::ViewerImGui("str"); 
	// this works   
	// viewer->run();
	// this doesnt ...
	std::thread th1(&Visualizer::StartViewer, this); 
}

void Visualizer::StartViewer()
{
	viewer->run();
}
`
The crash error is 
terminate called without an active exception
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile vertex shader!
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile fragment shader!
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to link shader program! (with GLSL '#version 150
')

When I run viewer->run()  directly, I can see the viewer window - but then run() is blocking and execution stops ..
Any idea how to fix that ?
Thanks
Lior

**Comment by LiangliangNan** [comment]
That viewer of Easy3D is based on GLFW that, by default, does not support multithreading. You may have a look at this: https://gist.github.com/Madsy/6980061
