### ISSUE TITLE
Octree visualization

### ISSUE THREAD

**Issue by fredricksolomon0** [LiangliangNan/Easy3D#28]
Is this possible to visualize octree data structure in Easy3d?. Because I am trying to insert my octree files, but it is showing in the compiler window that octree is working and it is not replicate in visualization window.

**Comment by LiangliangNan** [comment]
You can provide all the line segments of the octree as a `LinesDrawable`, then Easy3D will be able to visualize it. Please check and run this example: Tutorial_401_Drawable (that draws the bounding box of the model).
I would also be interested to include your program as an example in Easy3D (if you permit).

**Comment by fredricksolomon0** [comment]
Thanks. Once I will complete my work, I will update. Is this possible to draw bounding box on point cloud datasets.

**Comment by LiangliangNan** [comment]
Yes. The same as in example `Tutorial_401_Drawable`
