### ISSUE TITLE
Problem about the Tutorial_603_PointCloud_PlaneExtraction

### ISSUE THREAD

**Issue by wwtinwhu** [LiangliangNan/Easy3D#36]
Hello, Thank you for your work. I have been starred this repo for a long time. Recently, I have a demand to use the code about effcient ransac but I met some problem. As  it happens that I found you add a tutorial about the planeextraction.So I make and test it with the data you provide - building_cloud.bin. The problem is sometimes  that  the plane extraction can't work and the terminal output  as below. Sometimes works. It is so strange. Do you have any advice? Thank you very much! By the way ,I also use the source code of effcient ransac in my project, the problem in my project is that with same data and parameter, the number of detected plane can be 0 or other. It is also very strange. 

Failed one 
terminal output "ERROR IN GLOBAL REBUILD"
![2019-11-06 16-47-21 的屏幕截图](https://user-images.githubusercontent.com/28035224/68282794-48484d80-00b5-11ea-9ce0-4ca0242bd539.png)
Success one 
![2019-11-06 16-48-12 的屏幕截图](https://user-images.githubusercontent.com/28035224/68282865-67df7600-00b5-11ea-8cb0-4b34d82c44dd.png)

**Comment by LiangliangNan** [comment]
It seems that enabling OpenMP causes that problem (probably a bug in the RANSAC code when dealing with OpenMP). I disabled OpenMP and it should work now. Can you please check and let me know if it is solved (I don't have Ubuntu)?

**Comment by wwtinwhu** [comment]
> It seems that enabling OpenMP causes that problem (probably a bug in the RANSAC code when dealing with OpenMP). I disabled OpenMP and it should work now. Can you please check and let me know if it is solved (I don't have Ubuntu)?

Sorry for reply you so late. Just like you said, It is  the OpenMP that causes this problem. And when I disabled OpenMP in Ubuntu18.04, it works now. Thank you very much!

**Comment by LiangliangNan** [comment]
Thank you for the update (and in particular reporting this issue).
Good luck!
