### ISSUE TITLE
Cannot Compile BUILD_ALL After Successful Initial CMake Build

### ISSUE THREAD

**Issue by Camuvingian** [LiangliangNan/Easy3D#37]
Downloaded release V2.0 CMake build runs, generate the VS2019 solution files, this build fails with the following errors.

![image](https://user-images.githubusercontent.com/4823601/69730129-6c7cd480-111f-11ea-8cfe-5e820c890539.png)

![image](https://user-images.githubusercontent.com/4823601/69730279-a8b03500-111f-11ea-8bc8-5bf4446ad563.png)

et al. Can you please advise?

**Comment by LiangliangNan** [comment]
Can you post a snapshot of the first few errors in the Output tag?
--
Liangliang

**Comment by Camuvingian** [comment]
Attached is the full build output. Building using Win32 and the default solution file for ALL_BUILD. 

[easy3d_build_output.txt](https://github.com/LiangliangNan/Easy3D/files/3900820/easy3d_build_output.txt)

**Comment by LiangliangNan** [comment]
Can you try 64bits (I only tested with 64bit; and I don't have vs2019) and let me know it reports the same errors?

**Comment by Camuvingian** [comment]
I really need to use Easy3D as a library in an x86 based application. I have tried to com[pile using an x64 based configuration, but I still get errors. Any help you can offer would be most appreciated... 

![image](https://user-images.githubusercontent.com/4823601/69798415-2aa86880-11c9-11ea-9463-9ea199a92017.png)

**Comment by LiangliangNan** [comment]
Just want to make sure I didn't misunderstand: did you also encounter errors when compiling easy3d with 64-bit configuration, or when linking 64-bit easy3d against other x86 modules?

**Comment by Camuvingian** [comment]
Merely building - I cannot build targeting either configuration (x86 or x64).

**Comment by Camuvingian** [comment]
I want to build Easy3D as a x86 though (is this a possibility?) because I would eventually like to consume and use this code in an x86 application.

**Comment by LiangliangNan** [comment]
Grab the new code and it should compile :-(
More information: https://stackoverflow.com/questions/49607565/error-use-of-overloaded-operator-is-ambiguous-while-building-for-i386

**Comment by Camuvingian** [comment]
The very latest commit should compile? I will pull this now and have another go, Thank you very much for your time.

**Comment by LiangliangNan** [comment]
Thank you for reporting this issue.
Let me know if it still doesn't work.
