### ISSUE TITLE
Qt: LinesDrawable

### ISSUE THREAD

**Issue by kiyoshiiriemon** [LiangliangNan/Easy3D#41]
I'm trying to display lines on Qt. My problem is that nothing is displayed if I add LinesDrawable to a mesh (or a pointcloud). Here is a reproducible code (diff for Tutorial_303_Viewer_Qt).

https://pastebin.com/VqQpYKGi

If I build and run it in Debug, I see the following error messages.
```
debug : High - API - ERROR : GL_INVALID_OPERATION error generated. VAO names must be generated with glGenVertexArrays before they can be bound or used.
GL error: 
	file: vertex_array_object.cpp
	line: 83
	function: bind
	info: Invalid operation (The specified operation is not allowed in the current state)
debug : High - API - ERROR : GL_INVALID_OPERATION error generated. Array object is not active.
GL error: 
	file: drawable.cpp
	line: 275
	function: draw
	info: Invalid operation (The specified operation is not allowed in the current state)
```
Adding glGenVertexArrays() call didn't solve the problem.
My environment is Ubuntu 18.04 x64 with Geforce 1080.

**Comment by LiangliangNan** [comment]
It works on both  Windows and Mac. I don't have Ubuntu and couldn't reproduce the error :-(

**Comment by LiangliangNan** [comment]
I believe the error is due to that the OpenGL context is not current when you call OpenGL function (in your code).  Please surround your code with 
```
 viewer_->makeCurrent();
 // your code here
viewer_->doneCurrent();
```
Let me know if it still doesn't work.

**Comment by kiyoshiiriemon** [comment]
Thank you!  Now I see lines but the mesh isn't still displayed.
(the mesh is displayed if no LinesDrawable is added)
Do you have any idea?

**Comment by kiyoshiiriemon** [comment]
The above issue reproduces both on Mac and Windows (VS2019).

**Comment by LiangliangNan** [comment]
By default, all necessary drawables for rendering are created when executing `viewer_->addModel(model);`
In your case, a drawable already exists before creating the default drawables. Thus, the viewer skips creating the default drawables.

Two options to solve your issues:
Option 1: (without changing Easy3D) create your drawable after `viewer_->addModel(model);`.
Option 2: (changing the behavior of Easy3D). I did this and the new code has been committed. You can compare it to the previous version to see what I have changed.

**Comment by kiyoshiiriemon** [comment]
Now I understand what was happening.
I'll take option 2 cuz I like the new addModel API.
Thank you!
