### ISSUE TITLE
Rq: Scale

### ISSUE THREAD

**Issue by jigneshBadrakhiya** [LiangliangNan/Easy3D#42]
how to get model and camera scale?

**Comment by LiangliangNan** [comment]
Sorry. I didn't get your question.
Please be specific when you ask a question.

**Comment by jigneshBadrakhiya** [comment]
i means how to get camera scale? like getposition()

**Comment by LiangliangNan** [comment]
No, there is no “scale” parameter. 
A bit on how a camera works:
  - zoom in: moving the camera closer to the object;
  - zoom out: moving the camera away from the object.

**Comment by jigneshBadrakhiya** [comment]
i have a image of that object and apply tranformation matrix on object to rotate that object but fact is image and object not match its scaling issue.

**Comment by jigneshBadrakhiya** [comment]
My project is based on 
![Matchig](https://user-images.githubusercontent.com/15354871/70807567-cfd75980-1de3-11ea-9a24-3a4d46ba1f93.PNG)

**Comment by LiangliangNan** [comment]
You should have a technique to figure out the camera parameters (position, view direction, up vector...), which is out of the scope of Easy3D. 
I will close this issue that is irrelevant to Easy3D.
