### ISSUE TITLE
Huge (e.g., >1 billion) point cloud rendering

### ISSUE THREAD

**Issue by fredricksolomon0** [LiangliangNan/Easy3D#44]
Hi,
     So far I did octree, frustum culling and level of detail in this library. When I tried to load more than 2.5 million points, it kick me out from the debugging. Is this possible to handle large amount pointclouds in this library. Can you please give some suggestions?

**Comment by LiangliangNan** [comment]
I tried 100 M points (all loaded to the GPU) without a problem, but that is in Release mode.
Debug mode, as its name says, is just for debugging. So use small data for debugging.

For rendering huge data (e.g., 1000 M, or even more), you will need a strategy to avoid uploading all points to the GPU (use your octree-based frustum culling).

**Comment by fredricksolomon0** [comment]
You mean, may be we can send half of the points to the GPU right??If possible can you recommend any algorithm or procedure?

**Comment by LiangliangNan** [comment]
Yes. Sending partial data (the most important points) is the basic idea.
See the technique described in PoTree (which can render 100 billion+ points in real-time):
http://potree.org/downloads/converter_documentation.pdf

**Comment by fredricksolomon0** [comment]
Thank you so much. I will think about this. Can I close this issue?

**Comment by LiangliangNan** [comment]
You're welcome.
Leave this open.  Maybe sometime I will consider implementing multi-resolution in easy3d (but hard to say when).

**Comment by fredricksolomon0** [comment]
One quick question, do I need to use shaders for this task?

**Comment by LiangliangNan** [comment]
Generating a multi-resolution representation of the points has nothing to do with OpenGL, so no shaders.
