### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [LiangliangNan/Easy3D#46]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [DialogPointCloudSimplification::constructKdTree](https://github.com/LiangliangNan/Easy3D/blob/945f4e2d042c4b7abbce2ed21a11fc9381102a34/applications/Mapple/dialogs/dialog_point_cloud_simplification.cpp#L85 "DialogPointCloudSimplification::constructKdTree function")
- [PaintCanvas::cleanup](https://github.com/LiangliangNan/Easy3D/blob/0d68955363638bf4c8b62b9f32570921bbf7ee94/applications/Mapple/paint_canvas.cpp#L88 "PaintCanvas::cleanup function")
- [PointCloudIO_ptx](https://github.com/LiangliangNan/Easy3D/blob/bc703963956f4d6247b4fdc3b99159bd3b3cf14f/easy3d/fileio/point_cloud_io_ptx.cpp#L49 "Destructor for PointCloudIO_ptx")

**Comment by LiangliangNan** [comment]
Thanks for pointing out this. Indeed, many checks in Easy3D could be avoided.
However, for some special cases, e.g., the delete operator is overloaded, it may not be safe to simply delete without a check of the NULL condition.

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?
