### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [LiangliangNan/Easy3D#47]
Would you like to add more error handling for return values from functions like the following?
- [fclose](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream.") ⇒ [save_ppm](https://github.com/LiangliangNan/Easy3D/blob/df7d8c28d2ac7795cd5e4d30073995e3d91223c9/easy3d/fileio/image_io.cpp#L117)
- [ftell](https://pubs.opengroup.org/onlinepubs/9699919799/functions/ftell.html "Return a file offset.") ⇒ [load_obj](https://github.com/LiangliangNan/Easy3D/blob/2046190435808ad6a8f1f51a1ad9cf4a91946f52/easy3d/fileio/surface_mesh_io_obj.cpp#L366)

**Comment by LiangliangNan** [comment]
Hi, thanks (again)!
These functions are actually not used in Easy3D (some of them were written years ago) and should have been deleted already. I will find time to clean them, but for now, they are there just for a record and backup.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by LiangliangNan** [comment]
Sorry, I am a bit confused. Can you explain more?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by LiangliangNan** [comment]
Of course. So?

**Comment by elfring** [comment]
Are there any more update candidates to consider besides the source code places which became outdated somehow?

**Comment by LiangliangNan** [comment]
Sorry. I don't understand. How is it related to Easy3D?

**Comment by elfring** [comment]
Will a more detailed source code analysis point any remaining open issues out (besides the functions which should be deleted according to your feedback)?

**Comment by LiangliangNan** [comment]
So far no time to do such an analysis.

**Comment by elfring** [comment]
How are the chances to integrate corresponding tools into the evolving software development process?

**Comment by LiangliangNan** [comment]
what tools?

**Comment by elfring** [comment]
I suggest to take another look also at tools from the linked information sources.

**Comment by LiangliangNan** [comment]
I'd appreciate you can create a pull request. Easier for we both, no?

**Comment by elfring** [comment]
The software design possibilities are influenced by the selection of development tools.

**Comment by LiangliangNan** [comment]
so?

**Comment by elfring** [comment]
* Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "Software development with AspectC++?")?
* How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by LiangliangNan** [comment]
This is open source, I would appreciate you can submit a pull request.

**Comment by elfring** [comment]
Would you like to fiddle with pointcuts and aspects (after the offer of pull requests)?

**Comment by LiangliangNan** [comment]
Just submit and I will review.

**Comment by elfring** [comment]
I would appreciate if the application of the suggested development methodologies could be clarified before.
