### ISSUE TITLE
Viewer management

### ISSUE THREAD

**Issue by AleBasso80** [LiangliangNan/Easy3D#55]
Hello,
I would like to integrate your viewer to show a live point cloud stream in a wider application.
I have a few doubts:

1) I need to keep on updating the visualized point cloud while I receive the data from an active camera: can you suggest me the best way to do it?
2) If I close and then reopen the viewer I get this error even if the application keeps on working (apparently) fine: 

debug : High - API - ERROR : GL_INVALID_OPERATION error generated. Buffer name does not refer to an buffer object generated by OpenGL.
debug : High - API - ERROR : GL_INVALID_OPERATION error generated. Target buffer must be bound and not overlapped with mapping range.
debug : High - API - ERROR : GL_INVALID_OPERATION error generated. Buffer name does not refer to an buffer object generated by OpenGL.
debug : High - API - ERROR : GL_INVALID_OPERATION error generated. Target buffer must be bound and not overlapped with mapping range.
debug : High - API - ERROR : GL_INVALID_OPERATION error generated. Buffer name does not refer to an buffer object generated by OpenGL.
debug : High - API - ERROR : GL_INVALID_OPERATION error generated. Target buffer must be bound and not overlapped with mapping range.
E0612 19:56:27.232616  8642 vertex_array_object.cpp:79] GL error: 
        file: /media/xxx/Data/Libraries/Easy3D/easy3d/renderer/vertex_array_object.cpp
        line: 79
        function: bind
        info: Invalid operation (The specified operation is not allowed in the current state)

I'm not really able to undestand it. May you help me, please?

Thank you very much and congratulations for your great work!

**Comment by LiangliangNan** [comment]
Hi @AleBasso80,

Thanks for your interest in Easy3D. Let's try.

1. This depends on how big your data is in each frame and how fast the IO of your hardware is. You may always feel a delay if each frame contains millions (or more) of points. For common PCs or laptops, relatively small data (e.g., < 100, 000 points) can be handled in real-time.

   How to improve performance? 
   The main idea is to minimize the data transfer from CPU to GPU. You may have observed that this is done by calling `void Drawable::update_vertex_buffer(const std::vector<vec3> &vertices);` This API is quite easy for beginners, but no control/flexibility was provided. For your dynamic data, the performance can be improved by 
   - using another thread for preparing data (point vertices) in CPU;
   - calling `bool VertexArrayObject::create_array_buffer(...)` with "dynamic == true". This function is actually called in `Drawable::update_vertex_buffer(...)`;
   - You might have seen from the source code that each time when the data is updated the vertex buffer is first destroyed (by `release_buffer(...)`) and then a new vertex buffer is created (by `glGenBuffers(...)`). These repeated "destroy/create" should be avoided and you only need to call `glGenBuffers(...)` only once. So each time when you receive the data from a new frame, you only need to first bind the buffer (by `glBindBuffer(...)`) and then update the buffer (by `glBufferData(... , GL_DYNAMIC_DRAW)`).
 - The performance can still be improved by mapping the GPU memory to your RAM (by `glMapBuffer(....)`. This way, you can directly stream the data to GPU memory, avoiding temporally storing the data in RAM.

2. This requires more information to figure out the reason.
  - do you run the viewer through remote desktop software?
  - what is your OS, GPU, OpenGL version, GLSL version?
  - are there same/similar errors the first time you run the viewer?
  - do you have multi-threads (so after you close the viewer, some threads are still running)? Please check (e.g., on Windows using the Task Manager) if the viewer process (or relevant processes) is still alive after you close the viewer.

**Comment by AleBasso80** [comment]
Hello,
sorry for the late reply. 
I'm having some troubles, I need to go deeper into the source code. 
Thanks for your hints!
