### ISSUE TITLE
Mapple crashed when using `Delaunay Triangulation 2D (only XY)'

### ISSUE THREAD

**Issue by zhl8223** [LiangliangNan/Easy3D#56]
I compiled easy3d application `Mapple' using VC2017 x64. 
When I used the Delaunay Triangulation 2D (only XY) to create mesh, the application crashed.

**Comment by LiangliangNan** [comment]
Did you see any error message?
Possible to share the data so I can reproduce the crash?

**Comment by zhl8223** [comment]
My console window screenshot.
![image](https://user-images.githubusercontent.com/9796954/88471980-70c4f000-cf41-11ea-811a-45926a69ad4f.png)

You can get my test data from this link. 

> 链接：https://pan.baidu.com/s/1vhm2bQHRV3vD6Fmhx5Nc7A 
提取码：9n3o

**Comment by zhl8223** [comment]
My console window screenshot.
![image](https://user-images.githubusercontent.com/9796954/88471980-70c4f000-cf41-11ea-811a-45926a69ad4f.png)

You can get my test data from this link. 

> 链接：https://pan.baidu.com/s/1vhm2bQHRV3vD6Fmhx5Nc7A 
提取码：9n3o

**Comment by LiangliangNan** [comment]
I tried your data without any problems (it took only 4.4 ms). Please let me know how I can reproduce the error.
![test_small_delaunay_XY](https://user-images.githubusercontent.com/15526536/88475717-dfe71800-cf32-11ea-9cfa-4e36578874a4.png)

**Comment by zhl8223** [comment]
I tried your Mapple-release-20190308 on my PC, it is ok, not crashed.  You can try this small  program. It is always crashed on my PC.  Compiled on VC2017 x64.

`#include <easy3d/algo/delaunay_2d.h>
#include <easy3d/core/point_cloud.h>
#include <easy3d/fileio/point_cloud_io.h>
#include <easy3d/fileio/resources.h>
#include <easy3d/util/logging.h>

using namespace easy3d;

int main(int argc, char** argv) {
  // Initialize logging.
  logging::initialize(false, "", google::GLOG_INFO);

  // Read the point cloud from a known file.
  std::string file_name = "test_small.ply";
  PointCloud* cloud = PointCloudIO::load(file_name);
  if (!cloud) {
    LOG(ERROR) << "Error: failed to load model. Please make sure the file "
                  "exists and format is correct.";
    return EXIT_FAILURE;
  }

  std::cout << "point cloud has " << cloud->n_vertices() << " points"
            << std::endl;

  std::vector<easy3d::vec2> points;
  for (std::size_t i = 0; i < cloud->points().size(); ++i) {
    points.push_back(easy3d::vec2(cloud->points()[i]));
  }
  LOG(INFO) << "points: " << points.size();

  easy3d::Delaunay2 delaunay;
  delaunay.set_vertices(points.size(), (float*)points.data());
  LOG(INFO) << "triangles: " << delaunay.nb_triangles();

  // Delete the point cloud (i.e., release memory)
  delete cloud;

  return EXIT_SUCCESS;
}`

**Comment by zhl8223** [comment]
I know why the test program crashes. sizeof(unsigned long) is 4, not 8 on VC2017 x64. Just replace all the _unsigned long_ with **unsigned long long** in triangle.c will fix the problem

**Comment by LiangliangNan** [comment]
Thanks for the suggestion! Unfortunately, I don't have a Windows to test :-(
I've replaced all `unsigned long` with `uint64_t` so it is always 64 bit, but now I don't know if it will still work on 32bit windows. I would appreciate your help with a quick test.
