### ISSUE TITLE
Use Easy3D as an external library

### ISSUE THREAD

**Issue by jjpepper** [LiangliangNan/Easy3D#58]
I'm trying to use Easy3D from my own package, but I can't really understand how I'm supposed to get the 3rd party libraries right to make it compile.  I'm getting this error:

```Cannot open include file: '3rd_party/glog/glog/logging.h': No such file or directory```

But in `LiangliangNan\Easy3D\3rd_party\glog` there is no `glog` directory, so I don't understand how the code compiles in the examples.  Can you explain?  I added `LiangliangNan/Easy3D/3rd_party` to the include path in my CMakeLists.txt file but it's not found (because the glog directory doesn't contain a glog subdirectory).

What am I doing wrong?

**Comment by jjpepper** [comment]
I guess the real question here is how am I supposed to "use" Easy3D as an external library, when my own CMake project and source code is elsewhere, and I have a git clone of Easy3d.  I'm sure I must be missing something, but is there a way I can just add FindPackage(Easy3D) or something like that?

I actually solved the above issue by also adding the CMake build output directory into the include path as I found that's where the glog/glog/logging.h file is found by the tutorials.

So far I've done the following:

```
set(EASY3D_DIR C:/Users/jesse/source/repos/github/LiangliangNan/Easy3D)
set(EASY3D_3RD_PARTY_GLOG_SRC_DIR ${EASY3D_DIR}/3rd_party/glog/src)
set(EASY3D_3RD_PARTY_GLOG_SRC_WIN_DIR ${EASY3D_DIR}/3rd_party/glog/src/windows)
set(EASY3D_3RD_PARTY_DIR ${EASY3D_DIR}/out/build/x64-Release)
link_directories(${EASY3D_DIR}/out/build/x64-Release/lib)
add_executable(myExe ${MY_SOURCES})
target_link_libraries(myExe PUBLIC core renderer viewer glew glfw3 glog gui util fileio)
target_include_directories(miGeomGui 
    PUBLIC ${CMAKE_CURRENT_SOURCE_DIR} 
    PRIVATE ${EASY3D_DIR} ${EASY3D_3RD_PARTY_DIR} ${EASY3D_3RD_PARTY_GLOG_SRC_DIR} ${EASY3D_3RD_PARTY_GLOG_SRC_WIN_DIR})
target_compile_definitions(miGeomGui PRIVATE GLEW_STATIC)
```

But I'm still getting lots of link errors.   Please help :-)

**Comment by LiangliangNan** [comment]
You're right, the "glog/glog/logging.h" is located at the build output directory and you will need to specify the path to this directory. Google/glog generates header files in such a directory and I didn't want to change this default behavior. 

Providing "findPackage(Easy3D)" is a great idea. I am now swamped with teaching, but I will look into this later.  If you have any idea or have a draft implementation, I would be very happy to incorporate it into Easy3D.

If compilation succeeds but link errors, it must be that some libraries are missed in your "target_link_libraries(...)". Can you post the errors here?

**Comment by jjpepper** [comment]
Actually I got it building by just adding more and more libraries, but I
don’t understand why the tutorials don’t need a big list of libraries. I
must be missing something with how they work.

**Comment by LiangliangNan** [comment]
I think that must have something to do with the dependency of the modules (and to be honest, I don't know how to change this). 
Within Easy3D, the dependency hierarchy is known to the linker. But when Easy3D is used as an external library, the dependency hierarchy is lost, so all the libs have to be specified in "target_link_libraries(...)".

**Comment by LiangliangNan** [comment]
Todo: write a cmake config file for Easy3D, for 'find_package()'.

**Comment by LiangliangNan** [comment]
@jjpepper 
Now it is ready to use Easy3D as an external library. 
Add the following lines to your cmakelist file will do. Let me know if it doesn't work or anything that can be improved
```
find_package(Easy3D REQUIRED)
target_include_directories(${YOUR_APP_NAME} PRIVATE ${EASY3D_INCLUDE_DIRS})
target_link_libraries(${YOUR_APP_NAME} ${EASY3D_LIBRARIES})
```
