### ISSUE TITLE
Point cloud visualization only shows green color

### ISSUE THREAD

**Issue by minhpvo** [LiangliangNan/Easy3D#6]
I was trying to visualize the bunny.bin example using the code you provided in Quick glance section but the bunny is showed in green only. Could you please suggest what could have been wrong? I am using Windows OS.  --Thanks!

**Comment by LiangliangNan** [comment]
Hope you have solved the issue :-)
In case not, please sent me a snapshot of your rendering and the code you transfer data to GPU.

**Comment by minhpvo** [comment]
This is the code I used:

        PointCloud* cloud = new PointCloud;	// create a point cloud
	PointCloud::VertexProperty<vec3> colors = cloud->add_vertex_property<vec3>("v:color");
	
        FILE *fp = fopen("C:/temp/3dGL.xyz", "r");
	if (fp != NULL)
	{
		float x, y, z;
		int id, r, g, b;
		std::vector<vec3> rgb;
		while (fscanf(fp, "%d %f %f %f %d %d %d ", &id, &x, &y, &z, &r, &g, &b) != EOF)
		{
			cloud->add_vertex(vec3(x, y, z));
			rgb.push_back(vec3(1.0f / 255.f*r, 1.0f / 255.f *g, 1.0f / 255.f*b));
		}
		fclose(fp);

		int ii = 0;
		for (auto v : cloud->vertices())
			colors[v] = rgb[ii], ii++;
	}

	
	PointsDrawable* drawable2 = cloud->add_points_drawable("points");

	auto pointsPtr = cloud->get_vertex_property<vec3>("v:point");
	drawable2->update_vertex_buffer(pointsPtr.vector());
	auto normalsPtr = cloud->get_vertex_property<vec3>("v:normal");
	if (normalsPtr)
		drawable2->update_normal_buffer(normalsPtr.vector());
	auto colorsPtr = cloud->get_vertex_property<vec3>("v:color");
	if (colorsPtr)
		drawable2->update_color_buffer(colorsPtr.vector());

	viewer.add_model(cloud);
	viewer.run();

Using this code, I notice that in draw() of viewer.cpp, d->per_vertex_color() returns fail and I had to explicitly set it to be true.

**Comment by LiangliangNan** [comment]
If you want to render the point cloud with a uniform color, you need to call
  void set_default_color(const vec3& c); and
  set_per_vertex_color(false);
If you want to assign each point a color, you need to call
   update_color_buffer(...); // make sure the colors are valid
   set_per_vertex_color(true);
--
Liangliang
