### ISSUE TITLE
Consider adding prefix easy3d to build artifact names

### ISSUE THREAD

**Issue by 678098** [LiangliangNan/Easy3D#61]
For now several libraries builds in easy3d: algo, core, fileio, kdtree, util, renderer, gui, viewer. As a result corresponding binary items are being created like libalgo.a, libcore.a, ...
But such namings are not suitable for adding easy3d libraries in separate projects for several reasons:

1. Possible name collisions. For example "core" is too common name.
2. Not fully clear which libraries are added in projects. Let's suppose that we see in project libraries list something like "opencv_core core gui boost_system". It's not fully and instantly clear that "core" and "gui" are from easy3d. But with boost and opencv in such case everything is ok.
3. In build library directory there are libraries like "libglew.a", "libcore.a", so easy3d libs are mixed with 3rd party libs.

So probably adding prefix easy3d to artifact names will be a better style: easy3d_core, easy3d_gui, ...

**Comment by LiangliangNan** [comment]
Thanks for your insights and constructive suggestions.
I have also been thinking about similar things but never had the determination to realize these.

Now the changes have been implemented in the `dev` branch (not tested yet).  You are welcome to try/use it and feedback is always welcome and appreciated. I will work to improve it so it will appear in the next release.
Thanks again!

**Comment by LiangliangNan** [comment]
I am closing this issue. Feel free to reopen it if you find any issues or when you have other comments related to this.
Thank you again!
