### ISSUE TITLE
Use animated models

### ISSUE THREAD

**Issue by Bardo91** [LiangliangNan/Easy3D#62]
Is there any helper for rigging in the library? I am looking an easy to use library to show animated meshes. I like this library because it is really easy to use, but I cannot find if it is possible to use bones/animations and so on.

**Comment by LiangliangNan** [comment]
Unfortunately, the focus of Easy3D is not on animation. So the feature you want to have is not included.
Maybe I can include that in a future release (but I cannot promise). You are welcome to contribute to it :-)

**Comment by Bardo91** [comment]
Thanks for the quick answer. I am not an expert on animations, but If I manage to do it, it will be a pleasure to contribute. Cheers!
