### ISSUE TITLE
Shader link error

### ISSUE THREAD

**Issue by kylaro** [LiangliangNan/Easy3D#64]
(edit found solution, described in comments below)
Hello,

Thank you for creating this incredible tool, it has been very useful on my other computer.

I am on a new laptop running into a problem with the shaders as seen in the screenshots attached. I did not have this issue on my desktop. GPU is RTX 2080 on desktop. Laptop has RTX 2080 super max-q).

The Viewer does not render things that use the shaders such as point impostor spheres which is my primary goal. The console is rapidly spammed when the mouse is moved in the Viewer window. I am able to workaround by just adding the PointsDrawable to the Viewer and not setting impostor type.

I was not able to solve this problem with googling. I hope you have some insight into this.

Here is the console output for your Copy/Paste convenience:

```
2021-02-25` 18:29:58,702 ERROR [default] Type mismatch: Type of gl_ClipDistance different between shaders.
Out of resource error.
 - 'points/points_spheres_geometry_color'
debug : High - SHADER COMP - ERROR : SHADER_ID_LINK error has been generated. GLSL link failed for program 8, "": Type mismatch: Type of gl_ClipDistance different between shaders.
Out of resource error.
```

Pictures are just samples, I can provide more if you wish.
Thank you even if this cannot be solved!
![Tut201](https://user-images.githubusercontent.com/22779547/109238418-1fac0180-7799-11eb-9be5-c5a5b24c326b.PNG)
![Tut302](https://user-images.githubusercontent.com/22779547/109238419-20449800-7799-11eb-8630-387e9c46f498.PNG)
![Tut307](https://user-images.githubusercontent.com/22779547/109238421-20449800-7799-11eb-88cc-be3928bf206e.PNG)
![PointsDrawable_SPHERE](https://user-images.githubusercontent.com/22779547/109238422-20449800-7799-11eb-884b-02d4d5f0443a.PNG)
This last picture is from my code trying to set imposter type to PointsDrawable::SPHERE. Just commenting out "drawable->set_impostor_type(PointsDrawable::SPHERE);" will make there be no issues - probably because the shader isn't being used.

**Comment by kylaro** [comment]
I found the current settings the OpenGL is running with:
Vendor graphic card: Intel
Renderer: Intel(R) UHD Graphics
Version GL: 3.2.0 - Build 27.20.100.8783
Version GLSL: 1.50 - Build 27.20.100.8783

I will try to switch rendered to the dedicated gpu.

**Comment by kylaro** [comment]
I was able to switch it by: right click desktop -> nvidia control panel -> manage 3d settings -> global settings -> preferred graphics processor = high-performance nvidia processor

Vendor graphic card: NVIDIA Corporation
Renderer: GeForce RTX 2080 Super/PCIe/SSE2
Version GL: 3.2.0 NVIDIA 451.67
Version GLSL: 1.50 NVIDIA via Cg compiler

I no longer get the error.
However now I get this:

```
debug : Medium - API - Performance : Program/shader state performance warning: Vertex shader in program 9 is being recompiled based on GL state.
debug : Medium - API - Performance : Program/shader state performance warning: Vertex shader in program 9 is being recompiled based on GL state, and was not found in the disk cache
debug : Medium - API - Performance : Program/shader state performance warning: Vertex shader in program 9 is being recompiled based on GL state.
debug : Medium - API - Performance : Program/shader state performance warning: Vertex shader in program 9 is being recompiled based on GL state, and was not found in the disk cache
```

**Comment by kylaro** [comment]
I no longer get the API Performance error , it just went away for no reason it seems.

**Comment by LiangliangNan** [comment]
> I no longer get the API Performance error , it just went away for no reason it seems.

> I was able to switch it by: right click desktop -> nvidia control panel -> manage 3d settings -> global settings -> preferred graphics processor = high-performance nvidia processor
> 
> Vendor graphic card: NVIDIA Corporation
> Renderer: GeForce RTX 2080 Super/PCIe/SSE2
> Version GL: 3.2.0 NVIDIA 451.67
> Version GLSL: 1.50 NVIDIA via Cg compiler
> 
> I no longer get the error.
> However now I get this:
> 
> ```
> debug : Medium - API - Performance : Program/shader state performance warning: Vertex shader in program 9 is being recompiled based on GL state.
> debug : Medium - API - Performance : Program/shader state performance warning: Vertex shader in program 9 is being recompiled based on GL state, and was not found in the disk cache
> debug : Medium - API - Performance : Program/shader state performance warning: Vertex shader in program 9 is being recompiled based on GL state.
> debug : Medium - API - Performance : Program/shader state performance warning: Vertex shader in program 9 is being recompiled based on GL state, and was not found in the disk cache
> ```

These are warnings when you run the viewer in debug mode. In “Release”, they should disappear.

The errors is only with your integrated Intel graphics card (with OpenGL3.2 requested) ?
Can you try to request OpenGL 3.3 (in constructor of the viewer) to see if there is any difference?

(The error might be related to the major changes introduced in OpenGL3.3)

**Comment by kylaro** [comment]
It seems OpenGL 3.3 did not fix the issue.

![image](https://user-images.githubusercontent.com/22779547/109299939-7cd89f00-77fb-11eb-842f-6960858bd0fb.png)

OpenGL 4.1 also does not fix:
![image](https://user-images.githubusercontent.com/22779547/109300095-b90bff80-77fb-11eb-961b-6077e7fb1449.png)

```
window_ = create_window(title, samples, 4, 1, full_screen, resizable,
                                depth_bits, stencil_bits);
```

**Comment by LiangliangNan** [comment]
This is tricky because I don't have an Intel graphics card.
The 'gl_ClipDistance' has a float type in all shaders, so don't understand what "Type of gl_ClipDistance" means.
Is this the first error in the whole log/record (sometimes many errors might be due to a previous error)?

**Comment by kylaro** [comment]
Here is the beginning of the console. Note that "Welcome dome." is the output of the usage() function in Viewer.

![image](https://user-images.githubusercontent.com/22779547/109374829-ce297280-787d-11eb-9ecc-7884e66f43f8.png)

**Comment by LiangliangNan** [comment]
These are from running in Debug mode. 
Is there any difference when running the program in Release mode? I mean sill the link error "Type mismatch: Type of gl_ClipDistance different between shaders"?
