### ISSUE TITLE
pfm xyz, depth and normal map to 3D

### ISSUE THREAD

**Issue by abhishek31704** [LiangliangNan/Easy3D#66]
Hi, 

If I have XYZ normal map, the depth map and Height map stored in pfm file format. Is it possible to generate 3D models?

**Comment by LiangliangNan** [comment]
This sounds more like a reconstruction problem (I believe it is doable, e.g., convert the depth map into a point cloud and then apply the Poisson reconstruction method) but it is not relevant to any particular software library.

**Comment by abhishek31704** [comment]
I have received these depth and normal map from XYZ point cloud data available and wanted to reconstruct 3D. But, the above approach directly works on the point cloud, in that case for me, the conversion into pfm image normal and depthmap format seems irrelevant( it is like reverse engineering).
