### ISSUE TITLE
Req: About Rotation

### ISSUE THREAD

**Issue by jigneshBadrakhiya** [LiangliangNan/Easy3D#7]
implement Rotate model Only X axis and only Y axis method.
surface mesh vertices transform from rotation matrix method.
thanks.

**Comment by LiangliangNan** [comment]
Hi, did you ask for functions that can rotate the model around Y or X axis?
That's is simply a matrix-vector product. It is already implemented. Please check the mat.h file.

**Comment by jigneshBadrakhiya** [comment]
model rotate from mouse axis

**Comment by LiangliangNan** [comment]
Thank you for the suggestion. 
This may be added in a later release.

**Comment by jigneshBadrakhiya** [comment]
Thanks for the answer.
another thing is that make it easy3d support more 3d format like .ply, .xyz  etc.

**Comment by LiangliangNan** [comment]
These have already been implemented and will appear in the next release.
--
Liangliang

**Comment by LiangliangNan** [comment]
@jigneshBadrakhiya Now the constrained rotation and PLY file (and other standard formats) IO are in the current release.

**Comment by jigneshBadrakhiya** [comment]
Thanks for your support.

**Comment by LiangliangNan** [comment]
@jigneshBadrakhiya  Now screen axis constrained camera manipulation has been implemented. Usage:
>   Left drag:           Rotate the camera                           
>   Right drag:          Move the camera                             
>   'x' + Left drag:     Rotate the camera around horizontal axis    
>   'x' + Right drag:    Move the camera along horizontal axis       
>   'y' + Left drag:     Rotate the camera around vertical axis      
>   'y' + Right drag:    Move the camera along vertical axis         
>   'o' + Left drag:     Rotate the camera around ortho-screen axis
