### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by zhuhapeng** [LiangliangNan/Easy3D#73]
Sorry prof. I mainly want to use the mapple source code, so i build the easy3d project, unfortunately, i failed it. here, below shows the error . i use cmake3.14, qt 5.9.2, visual studio 2015, CGAL 5.0.  i wonder if it is the problem of these? 
![图片](https://user-images.githubusercontent.com/25865224/114362764-48058900-9baa-11eb-8ab7-71a2a2905b68.png)

**Comment by LiangliangNan** [comment]
Hi, showing the error list doesn't provide much useful information.
The 'Build' log is more useful.

- Please post the entire build log.
- Please post the content of your Mapple.rc
- `CGAL::Polygon_mesh_processing::merge_reversible_connected_components()` is introduced in CGAL5.1.

**Comment by zhuhapeng** [comment]
thanks very much for your reply prof.  i will try to use the lastest code and the higher version of qt and cgal.

**Comment by LiangliangNan** [comment]
Your Qt version is good, and only CGAL needs to be updated.
BTW, I've added checking the CGAL version during the CMake step. A warning will be given if an unsuitable version of CGAL is detected.
