### ISSUE TITLE
Unable to display vertices

### ISSUE THREAD

**Issue by MichaelChen77** [LiangliangNan/Easy3D#78]
Hi Liangliang,

I am using the easy3D as my main viewer program in my research work.
Recently I encounter a issue. When the surfacemesh object (.obj, .off..) loads in the viewer, I can't display the vertices. 
What I do is following:
1, open the model file and load it in the viewer;
2, click "Points" on the left panel and see the points attributes buttons;
3, "Drawable" spinbox select "vertices" (by default), click 'visible' check box;
And the viewer can't show the vertices.. And error message shows: [ERROR] drawable 'vertices': vertex buffer not created. 1
Could you please give me some hints on solving this issue?

Thanks!
Regards
Yihao

**Comment by MichaelChen77** [comment]
In addition, when I load in the surfacemesh, I also see the folloing error display in the IDE application output:
can't find linker symbol for virtual table for `easy3d::LinesDrawable' value
  found `std::_Vector_base<easy3d::TrianglesDrawable*, std::allocator<easy3d::TrianglesDrawable*> >::_Vector_base()' instead.
My OS is ubuntu 18.04, IDE is qt5.

**Comment by LiangliangNan** [comment]
- Do other models have the same issue? If not, please share the model here.
- I guess you’re using Mapple. Did you build Mapple from the source code or the prebuilt binaries were used?

**Comment by MichaelChen77** [comment]
Hi Liangliang,
I am terrible sorry that I just found and solve the problems.
I used to modify buffer.cpp because I want to add other visible vertices like 'locks', which in the buffer.cpp:
if (drawable->name() == "locks") {
                details::update_mesh_locked_vertices(model, drawable);
                return;
            }
I added 
if (drawable->name() == "schelling_points") {
                details::update_mesh_schelling_points_vertices(model, drawable);
                return;
            }
but i forget to keep the this 'return' inside the { }.
Sorry that my mistake wasted your your time.

By the way, I am also trying to display the faces with different color in the model. What I mean is that one entire face in the same color, the other entire face in the different color. But currently I can only set the face color by setting it's 3 vertices with same values ( via mesh->add_vertex_property<double>("v:xxx..")). 
However, this can only satisfy that one face is with the same color. As for the other faces, some of them may have different values in it's 3 vertices, which will cause the vertex can't display the entire face same color.
I also try to use mesh->add_face_property<double>("f:xxx..") to assign value on the face, but nothing happened.
I didn't find how to assign the value in the manual. Could you please give me some advice? 
Or should I create another topic and close this one?

**Comment by LiangliangNan** [comment]
No worries :)

For the other issue, you could add a per face color attribute or a per face integer attribute. Then in the rendering panel, choose the color or scalar field for visualization.
If you donot know how, create another issue.

**Comment by MichaelChen77** [comment]
> No worries :)
> 
> For the other issue, you could add a per face color attribute or a per face integer attribute. Then in the rendering panel, choose the color or scalar field for visualization.
> If you donot know how, create another issue.

Sure, thanks for your quick reply! I will try your advice by myself firstly. Thanks for you guidance again. 
I will close this issue here.
