### ISSUE TITLE
Build dependencies missing from documentation

### ISSUE THREAD

**Issue by vissarion** [LiangliangNan/Easy3D#79]
In the README it is stated that 
> For the core functionalities and the basic viewer, all dependencies have already been included in the distribution.

however there are some dependencies not included in the distribution such as the CGAL library that the user should install manually and a few libraries/packages that are usually are available via OS package managers. 

I manage to build on  `5.4.0-73-generic #82-Ubuntu SMP ` with gcc version `9.3.0` and cmake version `3.18.3` after install cgal 5.1 manually and 
```
sudo apt-get install libxinerama-dev libxrandr-dev libxcursor-dev libxi-dev
```
There are probably other dependencies that my system has met. 

I think it would be useful if all needed dependencies are listed in the documentation.

**Comment by vissarion** [comment]
This is part of this JOSS review https://github.com/openjournals/joss-reviews/issues/3255

**Comment by LiangliangNan** [comment]
The use of CGAL (and also Qt) is optional.
I have clarified this in the ReadMe file:

> Like most software, Easy3D depends on some third-party libraries. Easy3D has made this easier for the users by including the source code of most third-party libraries (for the core functionalities and the basic viewer), and it leaves very few optional (for a few additional features that are typically not needed by most users).
> 
> The optional third-party libraries are:
> 
> - CGAL (optional): Easy3D has implemented a few algorithms for advanced surface mesh processing, such as surface (re)orientation, detecting and resolving duplicate vertices/faces and self-intersection, and clipping/splitting/slicing surface meshes. To enable these features, CGAL must be installed and is visible to CMake. Without CGAL, these features are disabled by default and you can still use all other features.
> 
> - Qt (optional): Easy3D supports Qt for UI creation, which can help develop sophisticated applications for 3D data processing and visualization. You can switch on the CMake option EASY3D_ENABLE_QT to include the examples and applications that depend on Qt (e.g., Tutorial_202_Viewer_Qt and Mapple)

**Comment by vissarion** [comment]
I see. However, even if it is optional, if the user have it installed then cmake will try to include it by default and then if the version is of your installed cgal is <5.1 the cmake will complain. So the question here is: if I have already installed CGAL (version<5.1) in my system then how could I install easy3D ? As it is now I should either uninstall CGAL or upgrade to >=5.1. I think it would be useful to have a cmake flag that disables the inclusion of CGAL defaulted to disabled since CGAL is optional. 

The same issue could have been possible with `Qt` but I didn't experience it.

Also minimum supported versions of Qt and CGAL should be included in the README, as well as links to the repository where the user can download and build them.

**Comment by LiangliangNan** [comment]
Oh... Actually, an earlier version of Easy3D had that CMake option for CGAL :sob:

Anyway. I've added back the CMake option `EASY3D_ENABLE_CGAL`, allowing users to explicitly request CGAL. 

The main changes in the CMakeLists file:
```
# Build advanced features that require CGAL (>= v5.1)
option(EASY3D_ENABLE_CGAL    "Build advanced features that require CGAL (>= v5.1)"    OFF)
```

and

```
if (EASY3D_ENABLE_CGAL)
      find_package(CGAL REQUIRED)
      if (CGAL_FOUND)
          if (CGAL_VERSION VERSION_GREATER_EQUAL "5.1")
              set(EASY3D_HAS_CGAL TRUE)
              add_definitions(-DHAS_CGAL)
              message(STATUS "Found CGAL v${CGAL_VERSION}")
          else ()
              set(EASY3D_HAS_CGAL FALSE)
              message(ERROR "CGAL v${CGAL_VERSION} is found but Easy3D requires at least version 5.1. Please install CGAL v5.1 or later.")
          endif ()
      else ()
          set(EASY3D_HAS_CGAL FALSE)
          message(ERROR "Some advanced features require CGAL (v5.1 or later) but CGAL was not found. Easy3D will be built without these features. "
                  "You can set 'CGAL_DIR' to the directory containing 'CGALConfig.cmake' or 'cgal-config.cmake' to help find CGAL.")
      endif ()
  endif ()
```

And in the README file, the minimum supported versions of Qt and CGAL are also made clear.

**Comment by vissarion** [comment]
Thanks for addressing this!
