### ISSUE TITLE
Document explain

### ISSUE THREAD

**Issue by LittleByLittle2** [LiangliangNan/Easy3D#8]
Hi, I want to use this framework, but I found that there are not many materials. Can you give me some links?

And I would like to produce 2D image from mesh grid map in a camera frame, can this framework work?

Best,
Yu

**Comment by LiangliangNan** [comment]
> Hi, I want to use this framework, but I found that there are not many materials. Can you give me some links?
Currently, the documentation is almost empty. The only useful materials are the tutorials. It would suggest you go through all those tutorials. I will add a detailed reference manual in a later release (this is ongoing with major changes).

> And I would like to produce 2D image from mesh grid map in a camera frame, can this framework work?
Did you mean snapshots of the rendering?

**Comment by LittleByLittle2** [comment]
> Did you mean snapshots of the rendering?

Yeah.

**Comment by LiangliangNan** [comment]
Thanks! You can use
           glReadPixels(0, 0, width_, height_, format, GL_UNSIGNED_BYTE, buffer);	easy3d_debug_gl_error;
to grab the snapshot from the framebuffer.
I will add this in the next release.

**Comment by LittleByLittle2** [comment]
> Thanks! You can use
> glReadPixels(0, 0, width_, height_, format, GL_UNSIGNED_BYTE, buffer);	easy3d_debug_gl_error;
> to grab the snapshot from the framebuffer.
> I will add this in the next release.

I saw in Tutorial_12_RealCamera, there is function relative to camera pose setting, so can I combine them together to get current camera view screenshot?

Thanks

**Comment by LiangliangNan** [comment]
Yes. But that example has a bug: the view is different (not too much) from the real image. I am trying to figure out the problem. Hopefully I can fix it soon.

**Comment by LittleByLittle2** [comment]
> Yes. But that example has a bug: the view is different (not too much) from the real image. I am trying to figure out the problem. Hopefully, I can fix it soon.

Thank you for your work.

**Comment by LiangliangNan** [comment]
@LittleByLittle2 Now the RealCamera example works. Please check it out.

**Comment by LittleByLittle2** [comment]
> @LittleByLittle2 Now the RealCamera example works. Please check it out.

Great. Thank you.

**Comment by LiangliangNan** [comment]
@LittleByLittle2 now taking snapshots is available in the new release.
And a few rendering techniques are added.
