### ISSUE TITLE
DOIs are missing from JOSS manuscript

### ISSUE THREAD

**Issue by vissarion** [LiangliangNan/Easy3D#80]
DOIs are missing from JOSS manuscript

e.g. MeshLab: an Open-Source Mesh Processing Tool
http://diglib.eg.org/handle/10.2312/LocalChapterEvents.ItalChap.ItalianChapConf2008.129-136

**Comment by vissarion** [comment]
This is part of this JOSS review openjournals/joss-reviews#3255

**Comment by vissarion** [comment]
Also it seems that a reference to CGAL library which Easy3D depends on is missing.

**Comment by LiangliangNan** [comment]
Thanks for pointing out these.

DOIs have been added.
The reference to CGAL has also been added.

**Comment by vissarion** [comment]
Thanks!
