### ISSUE TITLE
Some community guidelines are missing 

### ISSUE THREAD

**Issue by vissarion** [LiangliangNan/Easy3D#82]
I cannot find clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

The following guide could be helpful

https://github.com/LiangliangNan/Easy3D/community

**Comment by vissarion** [comment]
This is part of this JOSS review openjournals/joss-reviews#3255

**Comment by LiangliangNan** [comment]
Thanks!

This has been added here (and is also referred to in the ReadMe):
https://github.com/LiangliangNan/Easy3D/blob/main/CONTRIBUTING.md

**Comment by vissarion** [comment]
Thanks!
