### ISSUE TITLE
Small issue on clamp in Mapple

### ISSUE THREAD

**Issue by MichaelChen77** [LiangliangNan/Easy3D#84]
Hi Liangliang,

recently I accidently set the clamp value pair (dummy_lower_percent and dummy_upper_percent) to an improper value pair (dummy_lower_percent + dummy_upper_percent > 100%). And I found that the viewer didn't handle this case smoothly:
![before_change](https://user-images.githubusercontent.com/31195921/121018898-83e75400-c7d1-11eb-8a25-6e4263c59b64.png)
So I modified the code in the easy3d/renderer/buffer.cpp. After changed, the Mapple now can handle this small case smoothly:
![after_change](https://user-images.githubusercontent.com/31195921/121019167-c27d0e80-c7d1-11eb-9dda-6f98260646c6.png)

The code I modified is in the buffer.cpp is from line 70 to 79:

Original code:
"

                if (min_value == max_value) { // if so, we cannot clamp
                    min_value = values.front();
                    max_value = values.back();
                }

                // special treatment for boolean scalar fields if the values are the same
                if (min_value == max_value && typeid(FT) == typeid(bool)) {
                    min_value = 0.0f;
                    max_value = 1.0f;
                }

After changing:
"

                if (min_value >= max_value ) { // if so, we cannot clamp
                    min_value = values.front();
                    max_value = values.back();
                }

                // special treatment for boolean scalar fields if the values are the same
                if (min_value >= max_value && typeid(FT) == typeid(bool)) {
                    min_value = 0.0f;
                    max_value = 1.0f;
                } 
"
Could you please check it when you are available?

**Comment by LiangliangNan** [comment]
Thanks. This change has been incorporated into the code.
Besides, the user-provided values will be checked and a warning will be issued if the values are not acceptable.

**Comment by MichaelChen77** [comment]
> Thanks. This change has been incorporated into the code.
> Besides, the user-provided values will be checked and a warning will be issued if the values are not acceptable.

You are welcome! It is glad to help make this project more robust.
