### ISSUE TITLE
req: Recognize

### ISSUE THREAD

**Issue by jigneshBadrakhiya** [LiangliangNan/Easy3D#9]
if possible,  implement recognize 3d model on images through rotation matrix.
thanks.

**Comment by LiangliangNan** [comment]
What does this mean?

**Comment by jigneshBadrakhiya** [comment]
![facec0b0716ff1efddc44c62eb3e07906b997c21](https://user-images.githubusercontent.com/15354871/56361603-67f55280-6205-11e9-8ed2-2cc96c316da2.jpg)

**Comment by LiangliangNan** [comment]
I guess you mean: given a 3D model and an image of the model, find the camera parameters such that the 3D model aligns with the image.
A future release will provide the implementation of some well-known algorithms for mesh/point cloud processing. But the main purpose of Easy3D is to provide an infrastructure for 3D data processing and visualization. What you proposed is interest, but it will have a lower priority and I cannot promise anything given my limited time.
