### ISSUE TITLE
About OpenGL version

### ISSUE THREAD

**Issue by loveq007** [LiangliangNan/Easy3D#90]
What is the minimum version of opengl supported?
The GPU of my computer is Intel HD Graphics 4000, it supports opengl 4.0, when I run the demo "Tutorial_301_Viewer", it crashed. The location of the crash is in the function ShaderProgram::set_uniform, when glProgramUniformMatrix4fv is called. I found glProgramUniform was introduced in opengl 4.1, So I don’t know what is the minimum version of opengl supported by Easy3D.

**Comment by LiangliangNan** [comment]
Which OS are you using?
A laptop is typically has two GPUs, is the Intel HD Graphics 4000 the one used? Or maybe an software renderer is used?
Can you paste the output/log of the program here?

**Comment by loveq007** [comment]
I'm using Easy3D 2.1, I use it on a desktop computer with only integrated graphics, the OS is Windows 7.
After updating the latest version of the intel graphics driver, this problem was solved.
Thank you for your sharing.
