### ISSUE TITLE
Memory error when use easy3d with open3d

### ISSUE THREAD

**Issue by yuecideng** [LiangliangNan/Easy3D#92]
Thank you for your work, and I it is helpful for my recent work.

Recently I want to use easy3d::renderer with QT to build a 3D data processing app, and I also use open3d as 3rdparty for some point cloud processing. However, I meet some memory error when runing a simple code,
![image](https://user-images.githubusercontent.com/42235877/134926938-bc3be9da-317a-4420-8f71-5aef59da2a88.png)

I used cmake to link open3d shared libs with the executable, but do not call any open3d api in the code, which is actually the tutorial your provided. As follow:
```
#include <easy3d/core/point_cloud.h>

using namespace easy3d;

int main(int argc, char** argv) {

	// Create a point cloud
	PointCloud* cloud = new PointCloud;

	// Add some points. Here we add 100 points on a 10*10 grid.
	for (float i=-5; i<5; ++i) {
		for (float j = -5; j < 5; ++j) 
			cloud->add_vertex(vec3(i, j, 0));// z = 0: all points are on XY plane
	}
	std::cout << "point cloud has " << cloud->n_vertices() << " points" << std::endl;

	// Delete the point cloud (i.e., release memory)
	delete cloud;

    return 0;
}

```
I can run this example correctly without linking with open3d.

The related environment infos:
- ubuntu 20
- open3d == 0.13.0
- gcc 8

**Comment by LiangliangNan** [comment]
This is quite weird!
To figure out the reason, can you let me know if the following works well？
   (1)   remove the dependence of Open3D (without linking to open3d shared libs), build and run it.
   (2)   if (1) still fails, grab the code from the Easy3D repository and start a new build, then run that example.
   (3)   if (2) still fails, I will try to find a machine with a similar configuration for further investigation.

**Comment by yuecideng** [comment]
It works well with the removal of Open3D linking

**Comment by LiangliangNan** [comment]
Then I guess there might be some symbols appearing in both Open3D and Easy3D libraries, which might confuse the linker.
I never had such an issue before. Maybe you can try removing `using namespace easy3d;` and always use `easy3d::`?

**Comment by yuecideng** [comment]
Actually I have tried this method but it didn't work. By the way, if I init a point cloud instance in stack (e.g. `eays3d::PointCloud cloud;` instead of in heap, I receive the following error:
![image](https://user-images.githubusercontent.com/42235877/135058087-baeb5594-62c9-4e15-89f1-2e9484416731.png)

I found that if use `new` to create point cloud, the program break when calling constructor, whereas in above method, the error happen when the program exit.

**Comment by LiangliangNan** [comment]
Can you post the full code (and I also assume no Open3D is linked against)?

**Comment by yuecideng** [comment]
case 1:
```
#include <easy3d/core/point_cloud.h>

int main(int argc, char** argv) {

	// Create a point cloud
	easy3d::PointCloud* cloud = new easy3d::PointCloud;

	// Add some points. Here we add 100 points on a 10*10 grid.
	for (float i=-5; i<5; ++i) {
		for (float j = -5; j < 5; ++j) 
			cloud->add_vertex(easy3d::vec3(i, j, 0));// z = 0: all points are on XY plane
	}
	std::cout << "point cloud has " << cloud->n_vertices() << " points" << std::endl;

	// Delete the point cloud (i.e., release memory)
	delete cloud;

    return 0;
}
```
case 2:
```
#include <easy3d/core/point_cloud.h>

int main(int argc, char** argv) {

	// Create a point cloud
	easy3d::PointCloud cloud;
	// Add some points. Here we add 100 points on a 10*10 grid.
	for (float i=-5; i<5; ++i) {
		for (float j = -5; j < 5; ++j) 
			cloud.add_vertex(easy3d::vec3(i, j, 0));// z = 0: all points are on XY plane
	}
	std::cout << "point cloud has " << cloud.n_vertices() << " points" << std::endl;

    return 0;
}
```

**Comment by LiangliangNan** [comment]
Not linked to Open3D libraries?
From the code, both should work. Can you try *re*building the program?

**Comment by yuecideng** [comment]
Maybe there is some misunderstandings... . Both the issues happen when I link with open3d, and work well if I only use easy3d.
Sorry about my description

**Comment by LiangliangNan** [comment]
Here are a few solutions for [Linking two shared libraries with some of the same symbols](https://stackoverflow.com/questions/6538501/linking-two-shared-libraries-with-some-of-the-same-symbols)

**Comment by yuecideng** [comment]
OK, I will try these solutions, thank a lot
