### ISSUE TITLE
Easy example for smoothing mesh surface in the code?

### ISSUE THREAD

**Issue by Davar1990** [LiangliangNan/Easy3D#97]
Thanks for creating such a wonderful easy to use library. I have gone through all the tutorials and despite having the option of pressing the key 'm' for smoothing the mesh surface, I wasn't able to find an easy to follow example of how to do this in the code. Is there an easy way that can be integrated in the "drawables" tutorial section to do so?

**Comment by LiangliangNan** [comment]
This can be simply done by calling to
`your_faces_drawable->set_smooth_shading(true);` 

The related code is here:
<img width="684" alt="Screen Shot 2021-11-11 at 10 45 28" src="https://user-images.githubusercontent.com/15526536/141276040-bafa638a-a3ff-4f52-a559-dd2fea74908f.png">

**Comment by Davar1990** [comment]
I'm sure there's something I'm missing as I'm still learning about this library. So my apologies if I raised this issue early on. But I tried `set_smooth_shading(true)` in the **Drawables** tutorial and it turned the surface all black. It seems like I messed up all the normals that way. 

![Capture](https://user-images.githubusercontent.com/17028943/141324135-3dfc571b-9041-4d5a-a6f8-9083e7882ec6.PNG)

**Comment by LiangliangNan** [comment]
Indeed, you're right. "Tutorial_301_Drawables" is a special example where normal information doesn't exist.
To have the "smooth" effect, you will need to pass per-vertex normal to GPU. The code shoud look like 
```c++
drawable->update_vertex_buffer(points);       // points are per-vertex vec3
drawable->update_normal_buffer(normals);   // normals are per-vertex vec3
drawable->update_element_buffer(indices);  
```
`indices` indicates how the vertices are connected to form faces. It stores  f1_v1, f1_v2, f1_v3, f2_v1, f2_v2, f2_v3 ... (i.e., all integer numbers denoting the vertex indices of all the faces).

**Comment by Davar1990** [comment]
I tried to feed the normals like this and it didn't work correctly. 

```
std::vector<easy3d::vec3> computeNormals(const std::vector<easy3d::vec3>& points, const std::vector<uint32_t>& indices) {
    
    std::vector<easy3d::vec3> normals(indices.size());

    for (int i = 0; i < indices.size(); i += 3) {

        easy3d::vec3 va = points[indices[i + 0]];
        easy3d::vec3 vb = points[indices[i + 1]];
        easy3d::vec3 vc = points[indices[i + 2]];

        easy3d::vec3 normVec = easy3d::normalize(easy3d::cross(vb - va, vc - va));
        normals[i + 0] = normals[i + 1] = normals[i + 2] = normVec;

    }

    return normals;
}
```
```
    // The coordinates of the vertices.
    const std::vector<vec3> &points = resource::bunny_vertices;
    // The indices represent how the vertices are connected to form triangles. The "bunny" is a triangle mesh, and thus
    // each consecutive three indices represent a triangle.
    const std::vector<unsigned int> &indices = resource::bunny_indices;
    
    const std::vector<easy3d::vec3>& normals = computeNormals(points, indices);

    //-------------------------------------------------------------
    // Create a TrianglesDrawable to visualize the surface of the "bunny".
    // For visualization, the point positions and the vertex indices of the faces have to be sent to the GPU.
    auto surface = new TrianglesDrawable("faces"); 
    // Upload the vertex positions of the surface to the GPU.
    surface->update_vertex_buffer(points);
    // Upload the vertex indices of the surface to the GPU.
    surface->update_element_buffer(indices);

    surface->update_normal_buffer(normals);
    surface->set_smooth_shading(true);

    // Add the drawable to the viewer
    viewer.add_drawable(surface);
```

**Comment by LiangliangNan** [comment]
This bunny has a set of separate faces, without topology information and it will not work.

with easy3d, the simple call to “add_model()” is sufficient to have that effect you need.

**Comment by Davar1990** [comment]
Got it. Will look into that carefully. Thanks :)
