### ISSUE TITLE
Binary for standalone Mapple for windows(.exe)

### ISSUE THREAD

**Issue by ZENGYIMING-EAMON** [LiangliangNan/Easy3D#98]
Hi, thank you for your great work! I learnt a lot from it and still want to learn more and deeper.

I am new to this project and want to try to use mapple on windows, after building I can run the tutorial .exe, but I can't find Mapple (.exe) just like the .app for mac in the release. Is there any releases I missed or how can I build mapple binaries myself on windows?

**Comment by LiangliangNan** [comment]
Thank you for your interest and kind words!

I don't have a Windows machine, so I myself am not able to produce the executable files for Windows, unfortunately. But I am pretty sure you can build it by yourself (many people have done this before). The only difference with building the examples in Easy3D is to enable the use of Qt (and some other optional 3rd party libraries such as CGAL if you need some advanced algorithms). Please have a look at the [Build Easy3D](https://github.com/LiangliangNan/Easy3D/blob/main/ReadMe.md#build-easy3d) section in the ReadMe file.

**Comment by LiangliangNan** [comment]
I believe this issue can easily be solved, so I am closing it now. If not, feel free to re-open it.
